In [ ]:
import pandas as pd
import os
import s3fs


fs = s3fs.S3FileSystem(
    client_kwargs={'endpoint_url': 'https://'+'minio.lab.sspcloud.fr'},
    key = os.environ["AWS_ACCESS_KEY_ID"], 
    secret = os.environ["AWS_SECRET_ACCESS_KEY"], 
    token = os.environ["AWS_SESSION_TOKEN"])

s3_folder = "s3://lab/PESSD/csv"

files = fs.glob(f"{s3_folder}/*.csv")

for file in files:
    fs.get(file, "data/"+(file.removeprefix("lab/PESSD/csv/")))

In [8]:
df = pd.DataFrame()
for file in os.listdir("data") : 
    temp = pd.read_csv("data/"+file)
    df = pd.concat([df,temp])

In [21]:
BI = df[(df["audio_file"]=="BI_wav.wav") & ((df["start"]<(15*60))|((df["start"]>(17.5*60))&((df["stop"]<(89*60))))|(df["start"]>(92.5*60)))]

In [23]:
BIF = df[(df["audio_file"]=="BIF_wav.wav") & ((df["start"]<(12.5*60))|((df["start"]>(14.5*60))&((df["stop"]<(76*60)))))]

In [25]:
BMF = df[(df["audio_file"]=="BMF_wav.wav") & ((df["start"]>(1.5*60)))]

In [26]:
BMH = df[(df["audio_file"]=="BMH_wav.wav")]

In [28]:
SCR = df[(df["audio_file"]=="SCR2_wav.wav") & ((df["start"]<(28*60)))]

In [29]:
d = pd.concat([BI,BIF,BMH,BMF,SCR])

In [48]:
d2.to_csv("data/test2.csv")

In [1]:
!pip install bertopic sentence-transformers umap-learn hdbscan

Requirement already satisfied: bertopic in /opt/python/lib/python3.13/site-packages (0.17.4)
Requirement already satisfied: sentence-transformers in /opt/python/lib/python3.13/site-packages (5.3.0)
Requirement already satisfied: umap-learn in /opt/python/lib/python3.13/site-packages (0.5.11)
Requirement already satisfied: hdbscan in /opt/python/lib/python3.13/site-packages (0.8.41)
Requirement already satisfied: numpy>=1.20.0 in /opt/python/lib/python3.13/site-packages (from bertopic) (2.4.2)
Requirement already satisfied: pandas>=1.1.5 in /opt/python/lib/python3.13/site-packages (from bertopic) (2.3.3)
Requirement already satisfied: plotly>=4.7.0 in /opt/python/lib/python3.13/site-packages (from bertopic) (6.6.0)
Requirement already satisfied: scikit-learn>=1.0 in /opt/python/lib/python3.13/site-packages (from bertopic) (1.8.0)
Requirement already satisfied: tqdm>=4.41.1 in /opt/python/lib/python3.13/site-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /opt/python/lib/python3.13/site-packages (from bertopic) (0.46.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (5.3.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (1.7.1)
Requirement already satisfied: torch>=1.11.0 in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (2.10.0)
Requirement already satisfied: scipy in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: packaging>=20.0 in /opt/python/lib/python3.13/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /opt/python/lib/python3.13/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /opt/python/lib/python3.13/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /opt/python/lib/python3.13/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in /opt/python/lib/python3.13/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /opt/python/lib/python3.13/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /opt/python/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/python/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /opt/python/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/python/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in /opt/python/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /opt/python/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /opt/python/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /opt/python/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/python/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: numba>=0.51.2 in /opt/python/lib/python3.13/site-packages (from umap-learn) (0.64.0)
Requirement already satisfied: pynndescent>=0.5 in /opt/python/lib/python3.13/site-packages (from umap-learn) (0.6.0)
Requirement already satisfied: joblib>=1.0 in /opt/python/lib/python3.13/site-packages (from hdbscan) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/python/lib/python3.13/site-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/python/lib/python3.13/site-packages (from pandas>=1.1.5->bertopic) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/python/lib/python3.13/site-packages (from pandas>=1.1.5->bertopic) (2025.3)
Requirement already satisfied: narwhals>=1.15.1 in /opt/python/lib/python3.13/site-packages (from plotly>=4.7.0->bertopic) (2.17.0)
Requirement already satisfied: six>=1.5 in /opt/python/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/python/lib/python3.13/site-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: setuptools in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (82.0.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /opt/python/lib/python3.13/site-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.4.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/python/lib/python3.13/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/python/lib/python3.13/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /opt/python/lib/python3.13/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /opt/python/lib/python3.13/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /opt/python/lib/python3.13/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/python/lib/python3.13/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/python/lib/python3.13/site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/python/lib/python3.13/site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /opt/python/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)

In [2]:
import pandas as pd
d = pd.read_csv("data/test.csv")

In [ ]:
#Pas nécessaire
import spacy
nlp = spacy.load("fr_core_news_sm", disable=["parser", "ner"])
d['lemmatized_text'] = [" ".join([token.lemma_ for token in doc]) for doc in nlp.pipe(d['text'])]

In [4]:
d

,Unnamed: 0,start,stop,text,main_speaker,main_g,audio_file
0,0,0.00,61.20,"En endroit, on est parti pour vivre encore un ...",SPEAKER_08,male,BI_wav.wav
1,1,61.20,103.60,"Oui, bonjour à tous, effectivement. Bienvenue ...",SPEAKER_02,male,BI_wav.wav
2,2,103.60,125.60,On imagine un Quentin qui aura envie de conser...,SPEAKER_12,male,BI_wav.wav
3,3,125.60,146.60,Moi je vais vous donner les numéros de Dossard...,SPEAKER_05,female,BI_wav.wav
4,4,146.60,150.60,Ouais l'équivalent à peu près de deux tours et...,SPEAKER_02,male,BI_wav.wav
...,...,...,...,...,...,...,...
1472,126,1611.68,1623.00,C'était raté sur la dernière course. La FP 4e ...,SPEAKER_11,male,SCR2_wav.wav
1473,127,1623.16,1633.56,"La Suède, qui revient à 3 secondes dès Nord-Vé...",SPEAKER_06,male,SCR2_wav.wav
1474,128,1634.88,1640.40,Ça va pas le mettre en confiance pour le début...,SPEAKER_10,male,SCR2_wav.wav
1475,129,1640.56,1645.64,C'était déjà la catastrophe à Nové-Mesto. Il a...,SPEAKER_06,female,SCR2_wav.wav
1476,130,1645.80,1688.76,Regardez cette Dream Team française. On a dans...,SPEAKER_11,male,SCR2_wav.wav

In [ ]:
# Install dependencies if needed
# pip install bertopic sentence-transformers umap-learn hdbscan

from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP

# Load CamemBERT embedding model
embedding_model = SentenceTransformer("dangvantuan/sentence-camembert-base")

STOPWORDS = [x.strip() for x in open('stopwords.txt').readlines()]

# Vectorizer for topic representation
vectorizer_model = CountVectorizer(
    stop_words=STOPWORDS,
    ngram_range=(1,2),
    min_df=2
)
#umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, random_state=42)
seed =  [
["émotion","larme","ému","joie","triste", "histoire","hommage"],
["famille","parents","ami", "personnelle"],
["attaque","montée","effort","énergie","relance","sprint"],        # tactique
["médaille","podium","victoire","champion","record","victoire","classement","premier","deuxième","troisième"],              # résultats
["bravo","chapeau","incroyable","monstrueux","magnifique","énorme"],        # admiration
["tir","cible","pénalité","debout","couché","faute"],                      # technique
["âge","ans","carrière","champion du monde","olympique","saison"],
["rapide","forme","expérience","solide","rapide","bon"],          # profil athlète
["devant","revient","prend la tête","écart","seconde", "temps","tour","intermédiaire","course","piste"] 
]
# Build BERTopic model
topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    language="french",
    calculate_probabilities=True,
    verbose=True,
    seed_topic_list=seed    
)

# Fit the model
topics, probs = topic_model.fit_transform(d2["text"])

# Show discovered topics
print(topic_model.get_topic_info())

# Show keywords for a specific topic
print(topic_model.get_topic(0))

# Visualize topics
topic_model.visualize_topics()

# Visualize topic hierarchy
topic_model.visualize_hierarchy()

#keybertopic, extrait phrases saillantes
#tester lda
#virer phrases nulles et refaire tourner
#pas virer -1 sauf si faible échantillon et checker
#checker si semi-superviser pour trouver thèmes

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5443.10it/s]
CamembertModel LOAD REPORT from: dangvantuan/sentence-camembert-base
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-03-16 11:44:12,445 - BERTopic - Embedding - Transforming documents to embeddings.
Batches:  57%|█████▋    | 26/46 [08:21<06:06, 18.34s/it]

In [98]:
t = pd.DataFrame({
    "text": d2['text'],
    "topic": topics,
    "topic_prob": probs.max(axis=1)  # max probability per text
})

In [99]:
t["topic"].value_counts()

topic
-1     508
 0      88
 1      86
 2      70
 3      49
 4      49
 5      44
 6      43
 7      41
 8      40
 9      35
 10     35
 11     34
 12     32
 13     32
 14     29
 15     28
 16     23
 17     21
 18     20
 19     20
 20     19
 21     17
 22     16
 23     15
 24     14
 25     13
 26     12
 27     11
Name: count, dtype: int64

In [67]:
topic_model.get_topic(4,full=True)

False

In [125]:
#1 : 4, 17, 18 retirés
#2 : 
for k in t[t["topic"]==26]["text"] : 
    print(k)

Oui, bonjour à tous, effectivement. Bienvenue à Antol, en Terre Selva. Moins de soleil qu'il y a deux jours, mais les Français, eh bien, sont au beau fixe. On est avec Marie Dorin, qui a été championne olympique multiple, championne du monde de Biathlon, et Frédéric Jean, qui était l'entraîneur de l'équipe de France féminine jusqu'à il y a 4 ans à Pékin. On était ensemble, avec vous Marie, au commentaire, et vous Fred, vous étiez dans l'encadrement de l'équipe de France, pour suivre le sacre de Quentin Fignon-Mayet. C'est vrai qu'aujourd'hui, les quatre Français peuvent jouer le podium et bien sûr la plus belle des médailles.
De retour à Antol Center Selva pour la première course individuelle de Biathlon. C'est 25e Jeu Olympique d'hiver. Jeux de Milan-Cortina. Vous n'avez rien manqué si vous nous rejoignez. Et bien, un seul français s'était lancé pour l'instant, Fabien Claude. Et bien, il nous fait du Fabien Claude, c'est-à-dire qu'il est en train de passer en tête aux intermédiaires.
Elle l'eut aussi. Et Boton, c'était le vainqueur de l'individuel d'ouverture de saison. Il avait remporté les 2 premières épreuves. Et Tristan avec Fabien Claude.
Oui, avec des scies. On refait toutes les courses, mais on coupe surtout du bois. Non, mais c'est le jeu du biathlon. Et c'est sûr qu'en fait, en vrai, une carrière, elle se joue souvent à une balle aussi. Là, il y a pas de regrets. Il y a une belle médaille d'argent au bout. Eric, il est jeune. C'est une course parfaite qu'il a faite. Bien sûr, il y en a une qui lui a échappé. Il peut seulement se dire, mais je suis sûre que ça va lui servir pour la suite. Il y a tout de bon, le matériel marche bien, la forme physique, elle est là. Il y a encore pas mal d'épreuves à passer et il ira chercher mieux, Eric.
Merci beaucoup, Tristan. Et ces jouissons loins d'être terminés pour Emilia Jacquelin. Dans un instant, le podium de cette épreuve de biathlon, donc en individuel, on le rappelle, médaille d'argent pour Eric Perrot, qui a terminé 2e derrière le Nord, Véjia, Botten. Ça fait maintenant 3 médailles pour l'équipe de France depuis le début de ces Jeux de Milan-Cortina. Dans un instant, c'est Cécile Grin qui pend le relais. Nous, on se retrouve tout à l'heure sur la chaîne France Télé Sport.
On n'est pas à Saint-Cyrus à l'occasion d'un match de l'Inter ou du Milan AC. On est bien en Thol, Santa Erselva, mais c'est un véritable stade de biathlon. L'un des plus beaux avec Rue Polding, avec ce qui est en train de devenir le Grand-Bornan, avec aussi Oslo, qui est aussi un endroit particulier. Et il y a, vous le voyez, ce public qui pousse avec Dimitrovac, la Bulgarie, en se souvenant que Gdafonska avait remporté le titre olympique en 1998 à Nagano pour aller Bulgar. Depuis, ça a un peu disparu des radars. Alors, c'est parti pour, on l'a dit, 15 kilomètres chez les femmes. C'était 20 hier, des boucles de 3 kilomètres. Et puis la particularité, c'est coucher debout, coucher debout.
Et puis avec la classe à 20 sur 20. C'est même plus un immense bravo. C'est un immense merci. Une admiration totale pour le biathlon français. Pour Cyril Burdell, entraîneur. Vous aviez connu cette joie avant qu'il vous remplace d'avoir des championnes olympiques. Avec, on pense, Justine Bresas-Boucher. Les équipes de France, même quand il y en a une qui se rate. Les autres sont présentes. Et ça fait une nouvelle fois de l'or. Un doublé.
Comme vous l'avez entendu France 2 prend une petite pause Donc nous on reste ensemble D'ici le début de la course Donc un petit tour Du Côté du Tableau des Médailles On se fait plaisir, on est tellement fier d'avoir battu notre record Qu'on se le regarde encore une fois On est à la cinquième place Est-ce qu'il arrive le tableau ? 10 médailles en biathlon Et 19 en tout C'est plus que la moitié C'est quand même incroyable Cette puissance qu'on a en biathlon D'ailleurs c'est quoi votre émission de biathlon préférée ? Parce que la mastarpe Je trouve ça assez fun J'ai vu tout à l'heure dans le chat, vous vous expliquez entre vous Il y a des spécialistes, j'ai vu 15 km et là ils partent tous en même temps Donc dites-moi là vous avez le plus d'adrénaline à regarder Allez on vous remet la course On est reparti pour cette mastarpe Allez !
Océane Michelon, 2e du sprint, titré avec le relais. Petit clin d'œil. C'est une jolie transition. Son cousin Florian sera guide sur les paralympiques guides d'Antony Chalanson sur le nordique. SkidFont et également Biathlon. Ils seront 3 français. Avec Benjamin Daviez, quadruple champion paralympique. Carl Tabouret, champion du monde sprint. Ça sera à partir du 6 mars. Les Jeux vont continuer. Pour l'instant, c'est la dernière épreuve de Biathlon avec une française en tête. Océane Michelon est derrière en embuscade. Lou Jean Monod et Julia Simon.
Voilà, 21 médailles pour la France. Cette titre est peut-être mieux. Ca va se jouer maintenant. On a vibré depuis le début ici, en retour, le Centre Selva. Et Océane Michelon, qui arrive, 23 ans, qui va avoir le tir le plus important de sa jeune carrière. Allez, Océane.
Les Françaises n'ont reporté qu'une médaille dans ce format de mastar de départ groupé en 5 éditions. C'était Justin Bresa-Boucher. Il y a 4 ans à Pékin. On aimerait avoir une autre médaille. Ça va dépendre maintenant. Elle vient de la fin de course pour Océane Michelon. Pour Julia Simon, Océane Michelon revient maintenant. Elle est solide, forte.
sur la planète biathlon pour finir ce relais. Julia Simon, Lisa Vitozzi, Maren Kierkeide et pour l'Allemagne,

In [28]:
mask = t[(t["topic"]!=4)&(t["topic"]!=17)&(t["topic"]!=18)]["text"]

In [29]:
d2 = d.merge(mask, on="text")

In [64]:
d2.merge(t,on="text")[d2.merge(t,on="text")["topic"]==18]

,Unnamed: 0,start,stop,text,main_speaker,main_g,audio_file,topic,topic_prob
498,398,4755.72,4757.72,C'est une belle histoire pour lui.,SPEAKER_05,female,BI_wav.wav,18,1.00000
588,515,6473.40,6476.36,"Il y a des leçons à tirer, malgré la déception...",SPEAKER_11,male,BI_wav.wav,18,1.00000
605,11,424.80,440.80,Juste le temps peut-être de saluer dans la raq...,SPEAKER_11,male,BIF_wav.wav,18,0.14816
937,342,4304.68,4312.68,C'est les belles histoires des jeux. Les belle...,SPEAKER_06,female,BIF_wav.wav,18,1.00000
948,353,4474.68,4496.68,"Oui, c'est vraiment... Bien évidemment, Trista...",SPEAKER_11,male,BIF_wav.wav,18,1.00000
1005,56,814.00,820.00,C'est long une Olympiade Avec toutes les émoti...,SPEAKER_04,male,BMH_wav.wav,18,1.00000
1041,97,1299.90,1307.90,La santé c'est le plus important. Elle peut êt...,SPEAKER_03,male,BMH_wav.wav,18,1.00000
1048,104,1369.90,1373.90,"Quand on connaît ses qualités, ça fend le cœur...",SPEAKER_04,female,BMH_wav.wav,18,1.00000
1621,173,1963.72,1972.56,"Va se laisser prendre par les émotions. Allez,...",SPEAKER_01,male,BMF_wav.wav,18,1.00000
1954,246,2668.36,2672.36,Oh les belles émotions.,SPEAKER_04,music,BMF_wav.wav,18,1.00000
2062,98,1244.00,1245.20,Il y a des sourires.,SPEAKER_09,male,SCR2_wav.wav,18,1.00000
2077,113,1420.24,1425.24,Et on prend le temps de savourer. Et nous auss...,SPEAKER_11,male,SCR2_wav.wav,18,1.00000

In [48]:
topic_model.get_topic(-1)

[('tir', np.float64(0.019705384158766548)),
 ('course', np.float64(0.01810100205230608)),
 ('julia', np.float64(0.016166922702569482)),
 ('secondes', np.float64(0.01581559885555621)),
 ('petit', np.float64(0.015216028128888991)),
 ('vraiment', np.float64(0.014750896397992897)),
 ('faut', np.float64(0.014264980364740047)),
 ('allez', np.float64(0.014103260774615873)),
 ('20', np.float64(0.01389915649281138)),
 ('aller', np.float64(0.013604787866193726))]

In [132]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")


sentence_embeddings = model.encode(d2["text"])
theme_embeddings = model.encode(themes)

sim = cosine_similarity(sentence_embeddings, theme_embeddings)
labels = sim.argmax(axis=1)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5220.97it/s]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [136]:
d2["labels"]=labels

In [147]:
d2[d2["labels"]==8]["text"]

0       En endroit, on est parti pour vivre encore un ...
3       Moi je vais vous donner les numéros de Dossard...
4       Ouais l'équivalent à peu près de deux tours et...
7       Il a un rôle important dans cette équipe. Donc...
9       On discutait hier justement dans la reconnaiss...
                              ...
1427    Et on prend le temps de savourer. Et nous auss...
1428    Elle vient de passer derrière le pas de tir. E...
1434    Simon l'a dit, Simon Fourcade, l'entraîneur de...
1440    La Suède, qui revient à 3 secondes dès Nord-Vé...
1441    Ça va pas le mettre en confiance pour le début...
Name: text, Length: 444, dtype: object

In [131]:
themes = []
for i in seed : 
    themes.append(" ".join(i))
themes

['émotion larme ému joie triste histoire hommage',
 'famille parents ami personnelle',
 'attaque montée effort énergie relance sprint',
 'médaille podium victoire champion record victoire classement premier deuxième troisième',
 'bravo chapeau incroyable monstrueux magnifique énorme',
 'tir cible pénalité debout couché faute',
 'âge ans carrière champion du monde olympique saison',
 'rapide forme expérience solide rapide bon',
 'devant revient prend la tête écart seconde temps tour intermédiaire course piste']

In [65]:
test = topic.merge(d, on="text")

In [67]:
test[(test["topic"]==10)|(test["topic"]==15)]

,text,topic,topic_prob,start,stop,main_speaker,main_g,audio_file
8,Pour vous en dire un petit peu plus sur la pis...,10,1.000000,289.60,345.80,SPEAKER_05,female,BI_wav.wav
9,On discutait hier justement dans la reconnaiss...,10,0.124827,345.80,356.40,SPEAKER_12,male,BI_wav.wav
11,Après c'est vrai que cette année il y a des st...,15,1.000000,374.20,386.60,SPEAKER_05,female,BI_wav.wav
13,"C'est un athlète solide, le jeune Suisse qui p...",15,0.238053,421.20,434.20,SPEAKER_12,male,BI_wav.wav
25,C'est un athlète qui a énormément d'expérience...,15,0.219121,604.20,622.20,SPEAKER_12,male,BI_wav.wav
26,"Cette année, il est un tout petit peu moins bo...",15,1.000000,622.20,634.20,SPEAKER_05,female,BI_wav.wav
28,"Fabien, c'est vraiment un skieur qui fait part...",15,1.000000,677.20,709.20,SPEAKER_05,female,BI_wav.wav
78,"Là, ça fait mal. On voit dans le regard qu'il ...",10,0.364798,1586.20,1595.20,SPEAKER_12,female,BI_wav.wav
93,On a l'impression qu'il y a les jambes qui tre...,10,1.000000,1724.20,1734.20,SPEAKER_05,female,BI_wav.wav
639,"Comme on l'avait dit pour le relais mixte, c'e...",10,0.152644,4025.84,4036.72,SPEAKER_05,female,BI_wav.wav
730,Complètement. C'est vrai que sur un individuel...,15,1.000000,4674.68,4727.28,SPEAKER_03,male,BI_wav.wav
754,Sur une piste exigeante où il faut sans cesse ...,10,1.000000,4900.40,4910.40,SPEAKER_12,male,BI_wav.wav
781,Un Boateng qui a été mais sacrément solide auj...,15,0.158726,5278.72,5290.12,SPEAKER_12,male,BI_wav.wav
783,Il lui a fallu une saison pour assimiler ce tr...,15,0.139592,5291.96,5312.84,SPEAKER_12,male,BI_wav.wav
786,"Olaq, oui, grand respect pour ce qu'il a pu fa...",15,1.000000,5577.64,5598.52,SPEAKER_04,male,BI_wav.wav
792,Comment avez-vous vécu cette course ? C'est un...,15,1.000000,5682.28,5750.04,SPEAKER_10,male,BI_wav.wav
794,"Écoutez, je fais un sport difficile. Pékin, ça...",15,1.000000,5756.48,5790.24,SPEAKER_10,male,BI_wav.wav
796,"Oui, je savais que... Avec l'expérience et la ...",15,1.000000,5793.48,5806.16,SPEAKER_10,male,BI_wav.wav
803,"Oui, avec des scies. On refait toutes les cour...",15,0.420427,5865.28,5900.56,SPEAKER_05,female,BI_wav.wav
813,C'est la révélation dans le sens où il a tenté...,15,0.187653,6146.16,6167.84,SPEAKER_12,male,BI_wav.wav
829,Oui. Je n'ai pas encore regardé les temps de s...,15,0.648638,6476.52,6512.36,SPEAKER_06,male,BI_wav.wav
839,C'est un format à part parce que c'est un form...,10,1.000000,210.80,236.80,SPEAKER_06,female,BIF_wav.wav
841,"Oui, il y aura toujours 4 tirs. On internera u...",10,1.000000,297.80,339.80,SPEAKER_10,male,BIF_wav.wav
842,"Oui, Alain, le stade d'hier, c'est une boucle,...",10,0.331937,339.80,378.80,SPEAKER_06,female,BIF_wav.wav
895,Lou après c'est sûr qu'elle a des grosses qual...,10,1.000000,1032.80,1062.80,SPEAKER_06,female,BIF_wav.wav
1032,"C'est dur ces individuels. Il faut tenir, il f...",10,0.340778,2667.48,2677.72,SPEAKER_06,female,BIF_wav.wav
1223,Après je peux vous dire que tous les efforts Q...,10,1.000000,392.00,412.00,SPEAKER_04,female,BMH_wav.wav
1225,La difficulté pour Fabien C'est qu'en fait com...,10,0.250248,430.00,450.00,SPEAKER_04,female,BMH_wav.wav
1232,Vous voyez là ça s'est vachement étiré Quand i...,10,0.510518,530.00,536.00,SPEAKER_04,male,BMH_wav.wav
1284,Ça va être compliqué pour Eric. On sent qu'il ...,10,0.529535,1080.90,1085.90,SPEAKER_04,female,BMH_wav.wav
1304,Là il n'est pas bien du tout déjà. Il se plain...,15,1.000000,1281.90,1299.90,SPEAKER_02,male,BMH_wav.wav
1362,Quentin derrière. Quentin est toujours costaud...,10,0.136500,1840.90,1855.90,SPEAKER_03,male,BMH_wav.wav
1410,"Quand on a ces qualités comme ça, d'être capab...",10,1.000000,2277.34,2285.02,SPEAKER_04,female,BMH_wav.wav
1507,35 ans sur sa piste à domicile. C'est un jubil...,10,0.327829,292.60,299.36,SPEAKER_02,male,BMF_wav.wav
1577,"Ca va partir. Selon les configurations du tir,...",10,0.308954,873.20,886.44,SPEAKER_04,male,BMF_wav.wav
1616,"La piste est difficile. Elle le sait, qu'il fa...",10,0.240924,1278.04,1286.40,SPEAKER_04,female,BMF_wav.wav
1650,Elles ont intérêt à partir. À ne pas laisser r...,10,0.255938,1598.32,1605.60,SPEAKER_04,female,BMF_wav.wav
1674,"L'enjeu, ça va être de ne pas penser aux résul...",10,0.609322,1856.40,1865.40,SPEAKER_04,female,BMF_wav.wav
1675,"Déposer le cerveau, mais garder le gros cœur. ...",10,1.000000,1865.56,1881.32,SPEAKER_01,male,BMF_wav.wav
1800,C'est pour ça que toutes les secondes d'avance...,10,1.000000,171.48,184.60,SPEAKER_11,male,SCR2_wav.wav
1818,Elle aura tout donné jusqu'au bout.,10,0.142104,398.28,400.04,SPEAKER_06,female,SCR2_wav.wav
1819,Il faut creuser les écarts. Il faut vraiment d...,10,0.452203,401.16,413.56,SPEAKER_10,male,SCR2_wav.wav
1835,Attention à Francis Caprus. On a l'impression ...,15,0.214445,621.60,635.76,SPEAKER_11,male,SCR2_wav.wav
1852,Je pense que ça sera compliqué pour eux d'espé...,15,1.000000,859.28,879.12,SPEAKER_06,female,SCR2_wav.wav