In [ ]:
import pandas as pd
import os
import s3fs


fs = s3fs.S3FileSystem(
    client_kwargs={'endpoint_url': 'https://'+'minio.lab.sspcloud.fr'},
    key = os.environ["AWS_ACCESS_KEY_ID"], 
    secret = os.environ["AWS_SECRET_ACCESS_KEY"], 
    token = os.environ["AWS_SESSION_TOKEN"])

s3_folder = "s3://lab/PESSD/csv"

files = fs.glob(f"{s3_folder}/*.csv")

for file in files:
    fs.get(file, "data/"+(file.removeprefix("lab/PESSD/csv/")))

In [8]:
df = pd.DataFrame()
for file in os.listdir("data") : 
    temp = pd.read_csv("data/"+file)
    df = pd.concat([df,temp])

In [21]:
BI = df[(df["audio_file"]=="BI_wav.wav") & ((df["start"]<(15*60))|((df["start"]>(17.5*60))&((df["stop"]<(89*60))))|(df["start"]>(92.5*60)))]

In [23]:
BIF = df[(df["audio_file"]=="BIF_wav.wav") & ((df["start"]<(12.5*60))|((df["start"]>(14.5*60))&((df["stop"]<(76*60)))))]

In [25]:
BMF = df[(df["audio_file"]=="BMF_wav.wav") & ((df["start"]>(1.5*60)))]

In [26]:
BMH = df[(df["audio_file"]=="BMH_wav.wav")]

In [28]:
SCR = df[(df["audio_file"]=="SCR2_wav.wav") & ((df["start"]<(28*60)))]

In [29]:
d = pd.concat([BI,BIF,BMH,BMF,SCR])

In [37]:
!pip install bertopic sentence-transformers umap-learn hdbscan

Collecting bertopic
  Downloading bertopic-0.17.4-py3-none-any.whl.metadata (24 kB)
Collecting sentence-transformers
  Downloading sentence_transformers-5.3.0-py3-none-any.whl.metadata (16 kB)
Collecting umap-learn
  Downloading umap_learn-0.5.11-py3-none-any.whl.metadata (26 kB)
Collecting hdbscan
  Downloading hdbscan-0.8.41.tar.gz (7.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 44.6 MB/s  0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.20.0 in /opt/python/lib/python3.13/site-packages (from bertopic) (2.4.2)
Requirement already satisfied: pandas>=1.1.5 in /opt/python/lib/python3.13/site-packages (from bertopic) (2.3.3)
Requirement already satisfied: plotly>=4.7.0 in /opt/python/lib/python3.13/site-packages (from bertopic) (6.6.0)
Requirement already satisfied: scikit-learn>=1.0 in /opt/python/lib/python3.13/site-packages (from bertopic) (1.8.0)
Requirement already satisfied: tqdm>=4.41.1 in /opt/python/lib/python3.13/site-packages (from bertopic) (4.67.3)
Collecting llvmlite>0.36.0 (from bertopic)
  Downloading llvmlite-0.46.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.0 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Downloading huggingface_hub-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting torch>=1.11.0 (from sentence-transformers)
  Downloading torch-2.10.0-3-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (31 kB)
Requirement already satisfied: scipy in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /opt/python/lib/python3.13/site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: packaging>=20.0 in /opt/python/lib/python3.13/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /opt/python/lib/python3.13/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /opt/python/lib/python3.13/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.2.28)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typer (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting safetensors>=0.4.3 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting filelock>=3.10.0 (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/python/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.2.0)
Collecting hf-xet<2.0.0,>=1.4.2 (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading hf_xet-1.4.2-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: anyio in /opt/python/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /opt/python/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in /opt/python/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/python/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Collecting numba>=0.51.2 (from umap-learn)
  Downloading numba-0.64.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)
Collecting pynndescent>=0.5 (from umap-learn)
  Downloading pynndescent-0.6.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: joblib>=1.0 in /opt/python/lib/python3.13/site-packages (from hdbscan) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/python/lib/python3.13/site-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/python/lib/python3.13/site-packages (from pandas>=1.1.5->bertopic) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/python/lib/python3.13/site-packages (from pandas>=1.1.5->bertopic) (2025.3)
Requirement already satisfied: narwhals>=1.15.1 in /opt/python/lib/python3.13/site-packages (from plotly>=4.7.0->bertopic) (2.17.0)
Requirement already satisfied: six>=1.5 in /opt/python/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/python/lib/python3.13/site-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: setuptools in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (82.0.0)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch>=1.11.0->sentence-transformers)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in /opt/python/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Collecting cuda-bindings==12.9.4 (from torch>=1.11.0->sentence-transformers)
  Downloading cuda_bindings-12.9.4-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparselt-cu12==0.7.1 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl.metadata (7.0 kB)
Collecting nvidia-nccl-cu12==2.27.5 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu12==3.4.5 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nvshmem_cu12-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.6.0 (from torch>=1.11.0->sentence-transformers)
  Downloading triton-3.6.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting cuda-pathfinder~=1.1 (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers)
  Downloading cuda_pathfinder-1.4.2-py3-none-any.whl.metadata (1.9 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/python/lib/python3.13/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /opt/python/lib/python3.13/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.3.1)
Collecting shellingham>=1.3.0 (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/python/lib/python3.13/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/python/lib/python3.13/site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading bertopic-0.17.4-py3-none-any.whl (154 kB)
Downloading sentence_transformers-5.3.0-py3-none-any.whl (512 kB)
Downloading transformers-5.3.0-py3-none-any.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 73.7 MB/s  0:00:00
Downloading huggingface_hub-1.7.1-py3-none-any.whl (616 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 616.3/616.3 kB 47.5 MB/s  0:00:00
Downloading hf_xet-1.4.2-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 84.3 MB/s  0:00:00
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 76.3 MB/s  0:00:00
Downloading umap_learn-0.5.11-py3-none-any.whl (90 kB)
Downloading filelock-3.25.2-py3-none-any.whl (26 kB)
Downloading llvmlite-0.46.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 79.3 MB/s  0:00:00m0:00:0100:01
Downloading numba-0.64.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 75.7 MB/s  0:00:00
Downloading pynndescent-0.6.0-py3-none-any.whl (73 kB)
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
Downloading torch-2.10.0-3-cp313-cp313-manylinux_2_28_x86_64.whl (915.6 MB)
   ━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━ 442.0/915.6 MB 86.0 MB/s eta 0:00:06

In [1]:
import pandas as pd
d = pd.read_csv("data/test.csv")

In [2]:
import spacy
nlp = spacy.load("fr_core_news_sm", disable=["parser", "ner"])
d['lemmatized_text'] = [" ".join([token.lemma_ for token in doc]) for doc in nlp.pipe(d['text'])]

In [7]:
groups = (d["main_g"] != d["main_g"].shift()).cumsum()

# merge consecutive texts
interventions = (
    d.groupby(groups)
      .agg({
          "main_g": "first",
          "text": " ".join
      })
      .reset_index(drop=True)
)

In [9]:
d

,Unnamed: 0,start,stop,text,main_speaker,main_g,audio_file,lemmatized_text
0,0,0.00,61.20,"En endroit, on est parti pour vivre encore un ...",SPEAKER_08,male,BI_wav.wav,"en endroit , on être partir pour vivre encore ..."
1,1,61.20,103.60,"Oui, bonjour à tous, effectivement. Bienvenue ...",SPEAKER_02,male,BI_wav.wav,"Oui , bonjour à tout , effectivement . bienven..."
2,2,103.60,125.60,On imagine un Quentin qui aura envie de conser...,SPEAKER_12,male,BI_wav.wav,on imaginer un quentin qui avoir envier de con...
3,3,125.60,146.60,Moi je vais vous donner les numéros de Dossard...,SPEAKER_05,female,BI_wav.wav,Moi je aller vous donner le numéro de Dossard ...
4,4,146.60,150.60,Ouais l'équivalent à peu près de deux tours et...,SPEAKER_02,male,BI_wav.wav,Ouais le équivaloir à peu près de deux tour et...
...,...,...,...,...,...,...,...,...
1472,126,1611.68,1623.00,C'était raté sur la dernière course. La FP 4e ...,SPEAKER_11,male,SCR2_wav.wav,ce être rater sur le dernier course . le FP 4e...
1473,127,1623.16,1633.56,"La Suède, qui revient à 3 secondes dès Nord-Vé...",SPEAKER_06,male,SCR2_wav.wav,"le Suède , qui revenir à 3 seconde dès Nord-Vé..."
1474,128,1634.88,1640.40,Ça va pas le mettre en confiance pour le début...,SPEAKER_10,male,SCR2_wav.wav,cela aller pas le mettre en confiance pour le ...
1475,129,1640.56,1645.64,C'était déjà la catastrophe à Nové-Mesto. Il a...,SPEAKER_06,female,SCR2_wav.wav,ce être déjà le catastrophe à Nové - Mesto . i...
1476,130,1645.80,1688.76,Regardez cette Dream Team française. On a dans...,SPEAKER_11,male,SCR2_wav.wav,Regardez ce dream Team français . on avoir dan...

In [16]:
# Install dependencies if needed
# pip install bertopic sentence-transformers umap-learn hdbscan

from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer

# Load CamemBERT embedding model
embedding_model = SentenceTransformer("dangvantuan/sentence-camembert-base")

STOPWORDS = [x.strip() for x in open('stopwords.txt').readlines()]

# Vectorizer for topic representation
vectorizer_model = CountVectorizer(
    stop_words=STOPWORDS,
    ngram_range=(1,2),
    min_df=2
)

# Build BERTopic model
topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    language="french",
    calculate_probabilities=True,
    verbose=True
)

# Fit the model
topics, probs = topic_model.fit_transform(d["text"])

# Show discovered topics
print(topic_model.get_topic_info())

# Show keywords for a specific topic
print(topic_model.get_topic(0))

# Visualize topics
topic_model.visualize_topics()

# Visualize topic hierarchy
topic_model.visualize_hierarchy()

#keybertopic, extrait phrases saillantes
#tester lda
#virer phrases nulles et refaire tourner
#pas virer -1 sauf si faible échantillon et checker
#checker si semi-superviser pour trouver thèmes

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5877.77it/s]
CamembertModel LOAD REPORT from: dangvantuan/sentence-camembert-base
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-03-13 16:53:04,853 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 47/47 [18:03<00:00, 23.05s/it]
2026-03-13 17:11:08,388 - BERTopic - Embedding - Completed ✓
2026-03-13 17:11:08,389 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-13 17:12:08,374 - BERTopic - Dimensionality - Completed ✓
2026-03-13 17:12:08,378 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-13 17:12:08,520 - BERTopic - Cluster - Completed ✓
2026-03-13 17:12:08,526 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-13 17:12:08,598 - BERTopic - Representation - Completed ✓

    Topic  Count                                               Name  \
0      -1    584                       -1_tir_course_julia_secondes
1       0    199                 0_julia_julia simon_simon_secondes
2       1    183              1_eric_perrault_eric perrault_quentin
3       2     57                 2_secondes_intermédiaire_repris_10
4       3     55                            3_tir_balle_balles_posé
5       4     39        4_applaudissements_allez_pioche_allez allez
6       5     35                5_grave_allez lou_dernière_retourne
7       6     33               6_relance_quentin_allez quentin_fini
8       7     30      7_fillon_quentin fillon_quentin_philippe horn
9       8     28                  8_course_tour_française_italienne
10      9     25                                  9_20_20 20_19_000
11     10     24                     10_faut_vraiment_piste_pousser
12     11     22                          11_skis_ski_bosse_relance
13     12     20                        12_tir_engagé_temps_francis
14     13     20               13_justine_julia_boucher_allez julia
15     14     19                    14_course_année_difficile_mieux
16     15     16              15_énorme_dingue_basculer_réalisation
17     16     15            16_coucher_faute coucher_euberg_endroit
18     17     13             17_vanessa_voight_voigt_vanessa voight
19     18     13          18_médaille_aller chercher_chercher_aller
20     19     12  19_émotions_belles_france télévisions_télévisions
21     20     12  20_couper monde_couper_chance couper_monde chance
22     21     12                21_agross_céline agross_céline_loin
23     22     11                    22_eric_tir eric_allez eric_tir

                                       Representation  \
0   [tir, course, julia, secondes, petit, vraiment...
1   [julia, julia simon, simon, secondes, france, ...
2   [eric, perrault, eric perrault, quentin, 20, p...
3   [secondes, intermédiaire, repris, 10, minutes,...
4   [tir, balle, balles, posé, tireur, tiré, tirs,...
5   [applaudissements, allez, pioche, allez allez,...
6   [grave, allez lou, dernière, retourne, rendez ...
7   [relance, quentin, allez quentin, fini, repris...
8   [fillon, quentin fillon, quentin, philippe hor...
9   [course, tour, française, italienne, ca tour, ...
10  [20, 20 20, 19, 000, pleine, 19 20, joue, déjà...
11  [faut, vraiment, piste, pousser, essayer, faut...
12  [skis, ski, bosse, relance, temps ski, monte, ...
13  [tir, engagé, temps, francis, couchers, rentré...
14  [justine, julia, boucher, allez julia, justin,...
15  [course, année, difficile, mieux, expérience, ...
16  [énorme, dingue, basculer, réalisation, grand,...
17  [coucher, faute coucher, euberg, endroit, 97, ...
18  [vanessa, voight, voigt, vanessa voight, huber...
19  [médaille, aller chercher, chercher, aller, ch...
20  [émotions, belles, france télévisions, télévis...
21  [couper monde, couper, chance couper, monde ch...
22  [agross, céline agross, céline, loin, passée, ...
23  [eric, tir eric, allez eric, tir, allez, compl...

                                  Representative_Docs
0   [Surtout quand on voit le niveau qui nous est ...
1   [Les papy-flingueurs, les tonton-flingueurs de...
2   [18 sur 20. Mais ça ne suffira pas. Eric Perra...
3   [Ca a été capable de recoller plus de 10 secon...
4   [le même temps sur le pas de tir. C'est pas un...
5   [Applaudissements, Applaudissements, Applaudis...
6   [C'est pas grave., Allez Lou., Oui, mais rende...
7   [Allez, remets-en. Allez, Quentin., Allez, Que...
8   [Il peut déclencher vite. Il y aura un tour po...
9   [S'il le fait, de cette course. ..., Ca va fai...
10  [Il va jouer le 20 sur 20., Il joue le 20 sur ...
11  [Après je peux vous dire que tous les efforts ...
12  [Et Eric est très fort sur les skis aussi., C'...
13  [Francis Capreuse qui a fait un bon effort. El...
14  [Attention, Justine., Julia et Justine pour cr...
15  [Oui, avec des scies. On refait toutes les cou...
16  [C'est énorme., C'est énorme. Quel honneur, Pi...
17  [La jeune allemande avait réussi le sans faute...
18  [Elle ski fort, Vanessa Voight. On la voit pas...
19  [Là il ne faut plus faire d'erreur pour Lou. E...
20  [Oui, c'est vraiment... Bien évidemment, Trist...
21  [Il a eu la chance de couper le monde. Il a eu...
22  [Céline Agross qui est passée au 4 km. Elle a ...
23  [Allez, Eric, on pousse. Une 17 d'avance quand...
[('julia', np.float64(0.029766915528693944)), ('julia simon', np.float64(0.025897737907758605)), ('simon', np.float64(0.02473571818850528)), ('secondes', np.float64(0.022400038353249545)), ('france', np.float64(0.02054848579255861)), ('lisa', np.float64(0.019563097045490255)), ('lou', np.float64(0.019220998419947056)), ('jeux', np.float64(0.01871518267205371)), ('monde', np.float64(0.018252024890238524)), ('biathlon', np.float64(0.017584984824980315))]

In [18]:
t = pd.DataFrame({
    "text": d['text'],
    "topic": topics,
    "topic_prob": probs.max(axis=1)  # max probability per text
})

In [20]:
t["topic"].value_counts()

topic
-1     584
 0     199
 1     183
 2      57
 3      55
 4      39
 5      35
 6      33
 7      30
 8      28
 9      25
 10     24
 11     22
 12     20
 13     20
 14     19
 15     16
 16     15
 17     13
 18     13
 19     12
 20     12
 21     12
 22     11
Name: count, dtype: int64

In [50]:
for t in t[t["topic"]==-1]["text"] : 
    print(t)

On imagine un Quentin qui aura envie de conserver son titre, mais face à lui, la startlist est belle. Il va falloir se méfier des Norvégiens qui ont sorti la grosse équipe aujourd'hui. Et attention, on sera dans le vif du sujet tout de suite avec l'expérience de Jakov Fak, le Slovene, et Fabien Claude, qui se lancera avec le 16. Donc il va falloir être attentif tout de suite.
Moi je vais vous donner les numéros de Dossard à suivre d'abord des Français. Donc il y a le Dossard 16, c'est Fabien Claude, donc Fabien qui est un gros skieur, un des meilleurs du circuit. Donc tout l'enjeu pour lui cette année, ça va être vraiment de mettre les balles au fond parce que voilà, c'est une course où il s'est une minute de pénalité par balle manquée. Donc tout de suite...
Ouais l'équivalent à peu près de deux tours et demi de pénalité.
Ouais voilà, c'est une grosse pénalité. Après aujourd'hui c'est quand même une piste pour les gros skieurs parce qu'on vous le détaillera un peu plus tard, mais il y a vraiment un effort continu à fournir tout au long des 4 kilomètres qu'ils auront à effectuer 5 fois. Ensuite du coup vous aurez le Dossard 38 de Éric Perrault, donc leader du classement général de la Coupe du Monde, leader du petit globe de l'individuel. Grand favori, même s'il a encore en face de lui du beau monde, il va falloir qu'il soit clean, qu'il soit propre sur les cibles, mais il sait parfaitement le faire. C'est un athlète qui maîtrise beaucoup ses émotions malgré son jeune âge et c'est vrai qu'on a de gros espoirs en Éric aujourd'hui. Ensuite vous aurez le Dossard 54 de Quentin Fillon-Mayet, qui du coup on ne le présente plus, c'est le multiple médaillé olympique des Jeux de Pékin. Et puis enfin pour le dernier français engagé sur cette course, il va y avoir Émilien Jacquelin avec le Dossard 60 qui avait brillé sur les Mondiaudantholls en 2020. Et c'est parti pour la course.
Ça y est tout pile. Victor Brand qui passe au 1er intermédiaire, après c'est lui qui a le chrono de référence donc on ne peut pas dire grand chose. Mais voilà, je vous disais jusqu'en haut de la bosse, en fait c'est 4 minutes d'efforts en continu.
On a même vu le suédois là, checker la montre, certainement sur un début de course, on est sur un 20 km ultra exigeant. Les athlètes évoluent pas à la même allure que sur un sprint, on est sur des allures qui ressemblent au seuil.
Et celui-là, il en a eu quelques-uns de podiums, notamment un podium olympique, une médaille d'argent. C'était en Corée en 2018 sur le sprint. Michel Krachmar, encore dans les 10 premiers lors des derniers championnats du monde, il avait pris la 8ème place. Il a 35 ans, un peu vieillissant, mais l'expérience et le savoir-faire tchèque qui est représenté et qui est en piste.
Il a fait même la différence sur la dernière étape de Coupe du Monde à la maison à Nove Mesto, où ils étaient allés chercher un podium en équipe. C'était lui, Michel Krachmar, qui avait fait la différence sur la fin de course. On imagine l'envie pour le tchèque aujourd'hui.
La Bulgarie avec Vasilev, c'est Elieff, qui est le porte-drapeau propre comme une figurine du biathlon vulgaire. Elieff qui était porte-drapeau lors de la cérémonie d'ouverture à Sand Siro, qui avait également fait une médaille en individuel.
J'allais dire, c'est quand qu'il nous montre un peu de ski, la mare du portier en départ. C'est presque la fin de la boucle, il est dans la montée du champ qui va rebasculer derrière sur le stade.
La grosse difficulté de cette 4 km. Il y a vraiment une longue bosse à l'extrémité de la piste. Et puis là, la fameuse montée du champ, c'est lui le plus rapide, Pidouchny, pour le moment, à l'intermédiaire. 6 secondes, un 2 mieux que Victor Brandt.
Et puis il vient de reprendre 30 secondes par rapport à Birkenthal, le laiton qui est parti 30 secondes devant lui, départ toutes les 30 secondes. Le premier coucher pour Brandt.
Il faut être très vigilant sur ce pas de tir. On a vraiment un bâtiment qui vient cacher cette masse d'air qui arrive de la gauche vers la droite. Là, les fanions actuellement bougent légèrement, qui vous poussent en tout cas les balles légèrement à droite. On a vu avec l'erreur de Victor Brandt, légèrement à droite. Cordon, Marie l'a signalé. Il y aura une minute de pénalité pour le suédois.
Les individuels apprécient des courses d'attente. Une minute, ça reste un 19 sur 20 si derrière c'est propre. Ça reste une belle course. Je serais étonnée que ça se gagne en dessous de 19, 20, 18 à la limite si il y a vraiment un gros temps de ski.
Surtout quand on voit la qualité de tir qu'on a eu sur le relais mixte. Quand on regarde le dernier individuel sur la dernière étape de la Coupe du Monde, il fallait tirer à 20 sur 20 pour gagner. Même 20 sur 20 pour être sur le podium.
C'est lui qui a pris l'éreine devant Pidrushny avec 5 secondes d'avance. Pidrushny, l'Ukrainien, lui a réalisé le sans-fotte sur le premier coucher. Ça lui permet de prendre la tête et Fabien devrait arriver au patir d'ici à les deux petites minutes.
Avec Jacob Vak qui, vous le voyez, dosseur 13 pour le Slovène d'origine croate, champion du monde 2012, qui arrive. Et qui va tenter lui aussi de faire le plein sur ce premier coucher. Particulé de l'individuel, coucher, debout, coucher, debout, on alterne.
Voilà, on rappelle que coucher, le diamètre des cibles est 4 cm5, debout c'est 11 cm5. Et que coucher, les athlètes ont tendance à s'installer sur leur numéro de dosseur, la cible sur laquelle ils ont effectué les réglages.
Pas de miracle pour Jacob Vak, une faute, pas très rapide sur les skis.
Ça va être compliqué.
Ça va être dur pour le Slovène. Il ne va pas jouer aujourd'hui. Malheureusement pour lui, dans très peu de temps, Fabien Claude va faire son entrée, il arrive sur le pas de tir d'ailleurs Fabien. On le voit qui a déjà remonté les 30 secondes qui le séparent de Braunhofer l'italien.
Il n'avait pas de précipitation.
Il faut prendre les informations avec le fagnon.
Ça commence mal pour Fabien.
C'est ce qu'on redoutait, un manque d'adresse au pas de tir parce qu'il est rapide sur les skis.
Il s'est fait piéger sur les deux premières, on l'a vu sortir la tête des éléments de visée. Peut-être qu'il a changé quelque chose dans sa position par rapport à son installation. On ne l'a pas vu cliquer. Ça ressortira 14e à 1,57 pour Fabien Claude avec ses deux minutes de pénalité. L'italien Braunhofer vient s'intercaler avec le son faute et est sorti deuxième à 23 secondes derrière Pidrouchny.
C'est dommage qu'on n'ait pas vu les impacts de balles de Fabien comme là on peut le voir à l'image. Ça nous aurait donné des indications de savoir si c'est des erreurs ou si c'est une tendance.
Et puis elle était longue cette dernière balle. Une très longue visée pour Lucas Fratscher. C'est piègeux, attention au niveau de ces visées là. Et on a Eric qui s'était lancé qui va emmener avec lui Lucas Fratscher qui est sorti deuxième, l'allemand.
Et puis surtout fraîchement médaillé d'or, donc il est en confiance le français.
Il me semble qu'il y a beaucoup de balles ratées en bas. Bas-droite, j'ai l'impression. Classique en fait la tendance.
Là il y a une grosse tendance bas-droite effectivement pour le finlandais.
Mais je regarde les fagnons, c'est vrai qu'il y a une masse d'air qui pousse vers la droite. Et naturellement comme les balles tournent dans le canon, il y a des tendances aussi verticales en fonction de l'influence de la masse d'air. Et un vent qui pousse vers la droite va avoir tendance à faire descendre les balles. Un vent qui pousse vers la gauche va avoir tendance à les faire monter. Ça c'est des tendances que les athlètes connaissent. C'est vraiment la difficulté de cet individuel en fait. De rentrer dans sa course, de ne pas trop être sur un faux rythme, d'arriver bien éveillé sur les cibles.
Alors que Victor Brandt continue son belle course.
Oui, ça va être intéressant pour lui en tout cas. Il y a les spectateurs, les fans suédois qui sont présents aussi dans les tribunes.
Et puis c'est surtout un des plus rapides du circuit. Johannes Dallet, un des plus rapides cette saison sur les skis.
Et puis sa dernière course, c'était la poursuite de Rupholding. Il n'est pas allé à Nové-Mestou. Il termine avec une victoire. Et c'est vrai qu'il a fait que des top 10 depuis Orphilzhen. Alors Pidrouchny, toujours devant. Celui qui avait fini au pied du podium des Jeulans dernier. Et bien évidemment, on vous tiendra au courant des temps de passage d'Éric Perrault. Qui n'est pas encore passé au 2,3 km. Et qui sera assurément suivi par les caméramagnes et la réalisation. Alors, Samuelson.
Alors, est-ce que Sébastien Samuelson sera dans un meilleur jour ?
Là, on est vraiment rentré dans le noyau dur. Le groupe rouge des meilleurs mondiaux qui s'élancent actuellement. Pidrouchny au tête.
Il est passé à côté. Rédibitoire, c'est trois erreurs.
Elle est loin, celle-là, la haute gauche.
On l'a vu.
Il est dans la difficulté. L'allemand, ça manque un petit peu de centrage.
Il est vraiment très rapide, le Français. On l'avait vu dans le portillon de départ avec de l'envie. Tout de suite, créé de la vitesse. Ça se confirme au premier intermédiaire. Neuf secondes plus vite que Philippe Horn, qui vient, lui, de prendre deux pénalités, l'allemand.
Et Lucas Hofer, très en forme cette année.
On le voit, c'est difficile.
Difficile à lâcher, cette première balle. C'est dur, on est sur une arrivée assez compliquée sur ce pas de tir. Il y a le phénomène de l'altitude aussi.
Dommage pour la dernière, mais c'était quand même une belle baston.
Et pour l'instant, l'information quand même, c'est que Eric Perrault va très vite. Voici le champion olympique en titre Quentin Fillon-Mayet. Revivre l'émotion d'il y a quatre ans et deux jours lorsqu'il était devenu champion olympique de l'individuel. Quentin, trois titres olympiques après son succès au sein du Relay Mix, ce dimanche.
20 kilomètres pour essayer d'aller conserver ce titre qui pour le moment lui appartient encore aux Français. Avec ce style bien à lui, à taper les bâtons, à s'exciter avant le départ, c'est une manière de se mettre dans sa course.
5 secondes et demi quand même. Quand on sait que Johannes Dallet c'est un des plus rapides du circuit.
Il est allé fort, il est allé vraiment fort là.
J'espère qu'il n'est pas parti trop vite. On va le voir rapidement parce qu'il va bientôt arriver sur le pas de tir.
Le plan 10 sur 10 pour Fratscher. Qui risque de ressortir devant. Patrick Braunhofer l'italien qui lui aussi est à 10 sur 10. Ca sera même un petit peu l'arrière pour Lucas Fratscher. À la sortie de ce deuxième tir. Et Philippe Navrat. Cette dernière balle.
Il ne la regarde pas jusqu'au bout. Le piège.
On vous avait annoncé Fabien à l'entrée de son deuxième tir. Fabien a fait une pénalité sur son tir de bout. Avec un total de 7 sur 10. Il est ressorti 11ème. Pour l'instant le français à 2 minutes 20.
Beaucoup d'erreurs quand même.
Johannes Dallet avec deux fautes. Siegfried Mazzey a compris l'entraîneur français des Norvégiens.
Compliqué, très compliqué. Il a certainement pas assez bloqué la respiration. Les deux sont partis à la volée.
Ça va lui coûter cher. C'est un individuel. Si ça tire pas bien, tout peut encore se jouer sur les skis. Et pour vous dire que Eric a toujours pas été battu sur les skis. Ils sont tous bien derrière.
Les Français sont bien rentrés dans la course.
Et un profil de piste qui convient parfaitement aux Français.
Samuel Son, une faute pour Zobel l'allemand. Il a craqué. 3 pioches et 2 tours de pénalité.
3 cibles réussis en 8 tirs. C'est vraiment un bon signe. Il est vraiment parti comme un poule et calmant sur la piste. Il vient de passer à 7 secondes. C'est Ponsiloma qui pourrait faire la bonne affaire.
Coup de chair la pénalité. 1 minute de rajouter.
Il a fait une faute.
Il est dans la même allure que Martin Oudahl. Il vient de passer à l'intermédiaire. Le Norvégien a tendance à partir sur la retenue.
Martin Oudahl est capable d'accélérer au fil de la course.
Une petite erreur. Une erreur pour Oudahl.
Martin Oudahl ressortit 23ème.
Erik Oudahl est debout.
Il va être dans le match. Samuelson qui perd du temps sur la piste. Il vient de passer à 42 secondes. 21 secondes de la tête de course.
14 sur 15. Il a eu 3 pénalités en tout. C'est un client sur la légride. Il a accéléré.
Il a eu le ténant du titre de la Coupe du monde.
Il a eu la chance de couper le monde. C'est un contexte particulier pour l'équipe de Norvège. Civert Bakken, l'un de leurs compatriotes, est décédé en Italie.
MICHA обыч de bachos de Ta pourtant les
Ils sont à deux. Ils ont tout intérêt à être ensemble jusqu'au bout. Certainement qu'ils vont être renseignés par les staffs au bord de piste. Essayer de se faire emmener par son coéquipier.
Le premier peut être à 15 sur 15.
Le local de l'Etat, Lucas Offer, habite sur place.
Il vit un calvaire.
Il est en train d'exploser. Quentin pour le debout.
Ca paraît compliqué après.
On est loin de la fin. La Suède plane sur cette course, cet individuel. Ponsiloma, c'était 12e des derniers jeux. Jamais un de top 10 en individuel. Des statistiques, cette saison. 80% au coucher, 75% au debout. Il est en tête pour l'instant.
Il va falloir attendre le dernier tir.
Fabien Claude ressortit de son 4e tir avec 16 sur 20. Il est provisoirement en tête, mais malheureusement, un cas de pénalité pour le Français. Ça fait beaucoup trop sur un individuel.
Je ne sais pas combien il a fait, je vous le dis.
Bravo pour l'Italien, 19 sur 20, qui aura fait une course pleine. Attention à la grid aussi. La grid peut ressortir en tête. Ca va se jouer à rien du tout.
Sur la la grid, qui a ressorti en tête de ce 2e tir, avec 3 secondes d'avance sur Pontsi-Luma. Philippe Navrat, lui, va ressortir de son 3e tir, 3e à 1.02 d'Eric Perot, avec le même nombre de pénalités que le Français.
Elle était longue, celle-là, la dernière. C'est dommage. Avec le 19, ça pouvait faire quelque chose de bien. Johannes Dallet, pour son 3e tir. ... Il s'est bien repris.
Il s'est vraiment remis dans sa course. Il va falloir le surveiller jusqu'au bout. S'il y a des ouvertures côté français, ça peut faire pour lui.
Il sort 4e, Johannes Dallet.
... Samuelson, toujours sur la piste, devant un 10 secondes d'avance sur Eric Perot. Johannes Dallet, 4e à la sortie de ce 3e tir.
Il avait accéléré. C'est lui qui a le 1er temps du 3e tour. Ca a accéléré pour les Norvégiens. Ils sont peut-être partis plus prudemment.
... Jasper Néline, qui peut aller chercher le 19 sur 20. Il est vite, le Suédois. Il était déjà...
Néline compliquée, mais Ponsiloma et Samuelson. Ces 2 compatriotes vont arriver
et ils ont la possibilité de ressortir devant. Il est là, Sébastien Samuelson, sur ce 3e tir. Il y a toujours du vert pour le Suédois.
C'est posé. On sent qu'il veut les mettre au fond.
Première erreur. ... Pour le Suédois.
Les deux Norvégiens.
Erik, il ne devrait pas tarder à arriver sur le pas de tir. Parce qu'il y a le dossard 33 qui est en train de tirer.
Et Martin Haldal.
On va surveiller quand même.
Oh, le champion ! Oh, le champion ! Il va ressortir en tête largement devant une de salopes. Mais derrière, il met la pression sur les Norvégiens, sur les Suédois, sur l'Allemand, et il est rapide sur les skis. Il a vraiment déclenché comme Lucky Luke. Il a vraiment fait attaquer un dernier tourboum.
Attention à Boughton, qui va répondre, présent, le Norvégien.
Allez, Eric ! Allez ! 4 km. Pour tout donner. C'est Fabien qui arrive avec 4 tours.
Mais on rappelle, c'était le meilleur tireur du circuit. Avant, il a pas fait le tir de la Coupe du monde.
Mais il faudra qu'il fasse 20 sur 20, qu'il déclenche vite et qu'il soit rapide sur les skis. Après, Boughton, c'est 97% de réussite sur le debout. Il va lui en rester un au Nord-Région.
On va vibrer jusqu'au bout.
Et non. Doublement non. Ca sera pas pour lui.
Jesper Néline devant Branhofer et Fabien Claude, malgré 4 fautes. In the Salaud, qui, dans quelques instants, avec le dossard 27, va s'emparer de la 1re place et qui jouera peut-être pour le podium. In the Salaud, regardez-le, 1 minute 40 d'avance.
Comme on l'avait dit pour le relais mixte, c'est une piste où on garde une vitesse élevée. Il y a des effets de groupe. Quand on a la chance de rester caché derrière un groupe, on peut bénéficier d'aspiration.
Il faut qu'il s'y arrête dans le Falandais. Là, c'est important, par contre.
David Sauvelet, regardez derrière. Le Finlandais volant in the Salo. Le Finlandais tirant surtout, puisqu'il a fait le 20 sur 20, qui est en train peut-être de s'envoler pour une médaille dans cette épreuve de l'individuel. Ça serait une belle surprise ou plutôt une belle récompense.
In the Salo, magnifique ce que fait le Finlandais. Il finit bien, en plus, le Finlandais. Regardez, 1 minute 44 d'avance par rapport à Néline. Ça peut faire le podium pour In the Salo.
Thomas O'Giacomel était ressorti 4e avec son 17 sur 20.
On entend Simon Fourcade. Il le sait, c'est la victoire, c'est l'or au bout.
Il faut tout voler, Eric. Il y a un duel à distance face à Bouton.
On a envie de pousser sur les bâtons. On a envie d'aider.
Il est comme une crie.
J'ai vu ses parents. Ils sont juste là. Ça va lui redonner de l'énergie.
La petite bosse de la passerelle. Il faut vraiment ventiler, ventiler, ventiler. Il va lui rester 500 m à Eric Perrault derrière.
Il n'aura plus qu'une bascule, plus qu'une relance à faire pour Eric. Relancer. Il était juste à droite, son papa, pour l'encourager. Allez, Eric, on pousse. Allez ! Il a peut-être eu une médaille d'or à la clé. Ça va dépendre de Johan Olaf Bouton.
Il donne tout pour l'instant, Eric Perrault. La descente. Passer sous la passerelle une nouvelle fois. Et arriver. Allez, Eric, allez. Il faut repatiner le plus vite possible.
Allez !
Elle est longue, cette arrivée. Interminable, interminable, cette traversée du stade. Il va plonger, là, Eric, dans la descente avant d'aller faire la dernière ligne droite.
A un moment où Eric Franchil a une arrivée, Bouton s'est installé sur le debout. Voilà, et Bouton qui arrive.
Je suis arrivé sur la tablette, là. Alex, il a sorti.
Il a perdu un petit peu de temps dans le tour précédent face à Eric. Attention, 11 secondes. Et puis, c'est un Norvégien contre un Franco-Norvégien, maintenant. 4 km, 11 secondes, 7. Ça va être un contre la montre. Et on va scruter et suivre la performance de Bouton, qui est habité par, bien évidemment, une histoire personnelle très forte. C'est lui qui a découvert le corps de son ami Sivert Bakken juste avant Noël lors d'un stage en Italie. Et ici, en Italie, il va peut-être aller chercher une médaille d'or pour lui, pour son copain, pour son pays. C'est une force supplémentaire qui lui est donnée, mais Eric Perrault a tout donné également. On va attendre jusqu'au bout.
Il passe vraiment loin devant le Finlandais.
Il n'y a pas de fleurs non plus sur les Jeux Olympiques. C'est une expression.
Si vous êtes les 6 premiers en Coupe du Monde, ça nous permet de respirer un petit peu, parce que là, on attend les 18 km 3, le temps de passage du doçard, bien évidemment, Boton.
Eric, on le revoit là, debout, qui nous a une fois de plus régalé.
Avec Fabien, forcément un petit peu déçu, j'imagine, de cet individuel et de premier tir qui vous met un peu dedans.
Il n'y a rien à dire. Il se reste un kilomètre 7, quand même. Un kilomètre 7.
Les Normégiens qui s'étaient ratés dans le relais mixte se ressaisissent bien.
Et puis, Giacomel. Thomas-Jacomel.
avec ses 3 pénalités. Regardez, 3 pénalités. Et quand même derrière Eric. C'est vrai qu'Eric a déclenché très vite sur le pas de tir.
Quentin pour le finish, il va aller chercher peut-être un top 8 aujourd'hui. 16 sur 20, malheureusement. Il ne va pas garder son titre olympique.
Mais une nouvelle fois dans un top 10, dans un top 8.

In [48]:
topic_model.get_topic(-1)

[('tir', np.float64(0.019705384158766548)),
 ('course', np.float64(0.01810100205230608)),
 ('julia', np.float64(0.016166922702569482)),
 ('secondes', np.float64(0.01581559885555621)),
 ('petit', np.float64(0.015216028128888991)),
 ('vraiment', np.float64(0.014750896397992897)),
 ('faut', np.float64(0.014264980364740047)),
 ('allez', np.float64(0.014103260774615873)),
 ('20', np.float64(0.01389915649281138)),
 ('aller', np.float64(0.013604787866193726))]

In [65]:
test = topic.merge(d, on="text")

In [67]:
test[(test["topic"]==10)|(test["topic"]==15)]

,text,topic,topic_prob,start,stop,main_speaker,main_g,audio_file
8,Pour vous en dire un petit peu plus sur la pis...,10,1.000000,289.60,345.80,SPEAKER_05,female,BI_wav.wav
9,On discutait hier justement dans la reconnaiss...,10,0.124827,345.80,356.40,SPEAKER_12,male,BI_wav.wav
11,Après c'est vrai que cette année il y a des st...,15,1.000000,374.20,386.60,SPEAKER_05,female,BI_wav.wav
13,"C'est un athlète solide, le jeune Suisse qui p...",15,0.238053,421.20,434.20,SPEAKER_12,male,BI_wav.wav
25,C'est un athlète qui a énormément d'expérience...,15,0.219121,604.20,622.20,SPEAKER_12,male,BI_wav.wav
26,"Cette année, il est un tout petit peu moins bo...",15,1.000000,622.20,634.20,SPEAKER_05,female,BI_wav.wav
28,"Fabien, c'est vraiment un skieur qui fait part...",15,1.000000,677.20,709.20,SPEAKER_05,female,BI_wav.wav
78,"Là, ça fait mal. On voit dans le regard qu'il ...",10,0.364798,1586.20,1595.20,SPEAKER_12,female,BI_wav.wav
93,On a l'impression qu'il y a les jambes qui tre...,10,1.000000,1724.20,1734.20,SPEAKER_05,female,BI_wav.wav
639,"Comme on l'avait dit pour le relais mixte, c'e...",10,0.152644,4025.84,4036.72,SPEAKER_05,female,BI_wav.wav
730,Complètement. C'est vrai que sur un individuel...,15,1.000000,4674.68,4727.28,SPEAKER_03,male,BI_wav.wav
754,Sur une piste exigeante où il faut sans cesse ...,10,1.000000,4900.40,4910.40,SPEAKER_12,male,BI_wav.wav
781,Un Boateng qui a été mais sacrément solide auj...,15,0.158726,5278.72,5290.12,SPEAKER_12,male,BI_wav.wav
783,Il lui a fallu une saison pour assimiler ce tr...,15,0.139592,5291.96,5312.84,SPEAKER_12,male,BI_wav.wav
786,"Olaq, oui, grand respect pour ce qu'il a pu fa...",15,1.000000,5577.64,5598.52,SPEAKER_04,male,BI_wav.wav
792,Comment avez-vous vécu cette course ? C'est un...,15,1.000000,5682.28,5750.04,SPEAKER_10,male,BI_wav.wav
794,"Écoutez, je fais un sport difficile. Pékin, ça...",15,1.000000,5756.48,5790.24,SPEAKER_10,male,BI_wav.wav
796,"Oui, je savais que... Avec l'expérience et la ...",15,1.000000,5793.48,5806.16,SPEAKER_10,male,BI_wav.wav
803,"Oui, avec des scies. On refait toutes les cour...",15,0.420427,5865.28,5900.56,SPEAKER_05,female,BI_wav.wav
813,C'est la révélation dans le sens où il a tenté...,15,0.187653,6146.16,6167.84,SPEAKER_12,male,BI_wav.wav
829,Oui. Je n'ai pas encore regardé les temps de s...,15,0.648638,6476.52,6512.36,SPEAKER_06,male,BI_wav.wav
839,C'est un format à part parce que c'est un form...,10,1.000000,210.80,236.80,SPEAKER_06,female,BIF_wav.wav
841,"Oui, il y aura toujours 4 tirs. On internera u...",10,1.000000,297.80,339.80,SPEAKER_10,male,BIF_wav.wav
842,"Oui, Alain, le stade d'hier, c'est une boucle,...",10,0.331937,339.80,378.80,SPEAKER_06,female,BIF_wav.wav
895,Lou après c'est sûr qu'elle a des grosses qual...,10,1.000000,1032.80,1062.80,SPEAKER_06,female,BIF_wav.wav
1032,"C'est dur ces individuels. Il faut tenir, il f...",10,0.340778,2667.48,2677.72,SPEAKER_06,female,BIF_wav.wav
1223,Après je peux vous dire que tous les efforts Q...,10,1.000000,392.00,412.00,SPEAKER_04,female,BMH_wav.wav
1225,La difficulté pour Fabien C'est qu'en fait com...,10,0.250248,430.00,450.00,SPEAKER_04,female,BMH_wav.wav
1232,Vous voyez là ça s'est vachement étiré Quand i...,10,0.510518,530.00,536.00,SPEAKER_04,male,BMH_wav.wav
1284,Ça va être compliqué pour Eric. On sent qu'il ...,10,0.529535,1080.90,1085.90,SPEAKER_04,female,BMH_wav.wav
1304,Là il n'est pas bien du tout déjà. Il se plain...,15,1.000000,1281.90,1299.90,SPEAKER_02,male,BMH_wav.wav
1362,Quentin derrière. Quentin est toujours costaud...,10,0.136500,1840.90,1855.90,SPEAKER_03,male,BMH_wav.wav
1410,"Quand on a ces qualités comme ça, d'être capab...",10,1.000000,2277.34,2285.02,SPEAKER_04,female,BMH_wav.wav
1507,35 ans sur sa piste à domicile. C'est un jubil...,10,0.327829,292.60,299.36,SPEAKER_02,male,BMF_wav.wav
1577,"Ca va partir. Selon les configurations du tir,...",10,0.308954,873.20,886.44,SPEAKER_04,male,BMF_wav.wav
1616,"La piste est difficile. Elle le sait, qu'il fa...",10,0.240924,1278.04,1286.40,SPEAKER_04,female,BMF_wav.wav
1650,Elles ont intérêt à partir. À ne pas laisser r...,10,0.255938,1598.32,1605.60,SPEAKER_04,female,BMF_wav.wav
1674,"L'enjeu, ça va être de ne pas penser aux résul...",10,0.609322,1856.40,1865.40,SPEAKER_04,female,BMF_wav.wav
1675,"Déposer le cerveau, mais garder le gros cœur. ...",10,1.000000,1865.56,1881.32,SPEAKER_01,male,BMF_wav.wav
1800,C'est pour ça que toutes les secondes d'avance...,10,1.000000,171.48,184.60,SPEAKER_11,male,SCR2_wav.wav
1818,Elle aura tout donné jusqu'au bout.,10,0.142104,398.28,400.04,SPEAKER_06,female,SCR2_wav.wav
1819,Il faut creuser les écarts. Il faut vraiment d...,10,0.452203,401.16,413.56,SPEAKER_10,male,SCR2_wav.wav
1835,Attention à Francis Caprus. On a l'impression ...,15,0.214445,621.60,635.76,SPEAKER_11,male,SCR2_wav.wav
1852,Je pense que ça sera compliqué pour eux d'espé...,15,1.000000,859.28,879.12,SPEAKER_06,female,SCR2_wav.wav