# Descriptive statistics

Our analysis is based on the gendered dimension of both journalists and athletes. 
Therefore, we provide descriptive statistics on the distribution of male and female journalists and athletes, as well as a cross-tabulated breakdown.

In [37]:
import pandas as pd
import os
from collections import defaultdict

# change the path based on the focused sport

sport_list = os.listdir("PESSD/results")

# stable_topics
stable = pd.DataFrame()
for sport in sport_list : 
    temp = pd.read_csv(f"PESSD/results/{sport}/stable_topics.csv", index_col="Unnamed: 0")
    temp = pd.DataFrame([
    {"topic": col, "words": [v for v in temp[col].dropna().tolist()]}
    for col in temp.columns
    ])  
    temp["topic"] = pd.to_numeric(temp["topic"])
    temp["sport"] = sport
    stable = pd.concat([stable,temp])

# text2topics
texts = pd.DataFrame()
for sport in sport_list : 
    temp = pd.read_csv(f"PESSD/results/{sport}/text2topics.csv", index_col="Unnamed: 0")
    temp["sport"] = sport
    texts = pd.concat([texts,temp])

# labels
label = pd.DataFrame()
for sport in sport_list : 
    temp = pd.read_csv(f"PESSD/results/{sport}/labels.csv", index_col="Unnamed: 0")
    d = defaultdict(list)
    for k, v in temp.to_dict(orient="records")[0].items():
        if pd.notna(v) : 
            d[v].append(k)
    temp = pd.DataFrame([
        {"label": k, "topic": v}
        for k, v in d.items()
    ])
    temp = temp.explode("topic")
    temp["topic"] = pd.to_numeric(temp["topic"])
    temp["sport"] = sport
    label = pd.concat([label,temp])

# add labels to texts
texts = texts.merge(label, how="left", on=["sport","topic"])

# add stable topics
sport_topics = stable.groupby("sport")["topic"].apply(set).to_dict()

for sport, topics in sport_topics.items():
    texts.loc[(texts["sport"]==sport) & (texts["topic"].isin(topics)), "stable"] = True

Now, let's join metadata in order to obtain gender of athletes.

In [2]:
df["ID"] = df["audio_file"].str.replace("_wav.wav","")
df = df.merge(pd.read_csv("metadata.csv", sep=","), on="ID")
df

,start,stop,text,main_speaker,main_g,audio_file,ID,g_ath
0,0.00,12.20,"Deux Français, on va prier en ce dimanche pour...",SPEAKER_02,male,BAH_wav.wav,BAH,H
1,12.20,28.80,"Ouais, ça... Pile au moment où Bouton lance un...",SPEAKER_03,male,BAH_wav.wav,BAH,H
2,28.80,31.80,"Et surtout dans cette zone, oui.",SPEAKER_08,male,BAH_wav.wav,BAH,H
3,31.80,38.80,"Le travail des techniciens, on voit la glisse ...",SPEAKER_02,male,BAH_wav.wav,BAH,H
4,38.80,44.80,On va arriver au deuxième tir. J'ai l'impressi...,SPEAKER_08,female,BAH_wav.wav,BAH,H
...,...,...,...,...,...,...,...,...
3179,2597.08,2604.40,"Vobornikova, ils attendaient une médaille depu...",SPEAKER_02,male,BMF_wav.wav,BMF,F
3180,2604.56,2614.76,Qui est ici? On avait cru pendant quelques ann...,SPEAKER_01,male,BMF_wav.wav,BMF,F
3181,2614.92,2656.40,qui vient chercher cette médaille de bronze. J...,SPEAKER_02,male,BMF_wav.wav,BMF,F
3182,2656.40,2661.76,Et Ossiane qui parle tout le temps de manger. ...,SPEAKER_00,female,BMF_wav.wav,BMF,F
3183,2661.76,2710.56,"Ses adversaires, Marie, aujourd'hui. Et regard...",SPEAKER_02,male,BMF_wav.wav,BMF,F

## Descriptive statistics

First, we want to see what is the total duration of the live commentary and how it is distributed among men and women journalists.

In [3]:
# Duration of each segment
df['duration'] = df['stop'] - df['start']

# Total duration
print("Total:")
print(df['duration'].sum() / 60) 

# Journalists
print("Journalists:")
print(df.groupby('main_g')['duration'].sum() / 60)

Total:
648.3223333333334
Journalists:
main_g
female      104.878000
male        526.731000
music         9.795333
noEnergy      1.748667
noise         5.169333
Name: duration, dtype: float64

Now we want to look at the number of different events based on the gender of athletes (mixt events also are included).

In [4]:
print(df.groupby('g_ath')['duration'].sum() / 60)

g_ath
F    239.291667
H    344.645667
M     64.385000
Name: duration, dtype: float64

Finally, we make a cross tabulation of both journalists' and athletes' gender.

In [5]:

# cross
print("\n Duration (minutes): ")
cross = df.pivot_table(
    values='duration',
    index='main_g',
    columns='g_ath',
    aggfunc='sum'
) / 60
print(cross.round(1))

 Duration (minutes):
g_ath         F      H     M
main_g
female     41.9   51.2  11.8
male      191.8  283.1  51.8
music       2.8    7.0   NaN
noEnergy    NaN    1.3   0.4
noise       2.8    2.1   0.3

Now, we do similar descriptive statistics by replacing time by number of sentences as a unit of analysis.

In [6]:
# dividing texte into sentences
df["text"] = df["text"].apply(lambda x : x.split(". "))
df = df.explode("text")

By athletes' gender:

In [7]:
g_ath_counts = df.groupby('g_ath').size()
print(g_ath_counts)
print((g_ath_counts / g_ath_counts.sum() * 100).round(1))

g_ath
F    3292
H    4830
M     907
dtype: int64
g_ath
F    36.5
H    53.5
M    10.0
dtype: float64

By speakers' gender:

In [33]:
main_g_counts = df.groupby('main_g').size()
print(main_g_counts)
print((main_g_counts / main_g_counts.sum() * 100).round(1))

main_g
female      3844
male        8210
music        224
noEnergy      59
noise        149
dtype: int64
main_g
female      30.8
male        65.8
music        1.8
noEnergy     0.5
noise        1.2
dtype: float64

Cross tabulation:

In [8]:
df_clean = df.reset_index(drop=True) # doublon index issues
print(pd.crosstab(df_clean['main_g'], df_clean['g_ath']))

g_ath        F     H    M
main_g
female     688   805  194
male      2547  3903  707
music       39    82    0
noEnergy     0    19    4
noise       18    21    2

## Sentences: descriptive statistics

Now we compare the average length (in words) and their standard deviation for each type of speaker.

In [9]:
df['text'].str.split().str.len().groupby(df['main_g']).agg(['mean', 'std']).round(1)

          mean   std
main_g
female    11.2  10.9
male      12.0  11.5
music      9.3  11.5
noEnergy   6.6   5.6
noise      8.3  10.1

Gender of athletes:

In [45]:
df['text'].str.split().str.len().groupby(df['g_ath']).agg(['mean', 'std']).round(1)

       mean   std
g_ath
F      11.6  10.2
H      12.1  11.1
M      12.1  10.0

And in general:

In [44]:
df['text'].str.split().str.len().agg(['mean', 'std']).round(1)

mean    12.0
std     10.7
Name: text, dtype: float64

In [10]:
df['word_count'] = df['text'].str.split().str.len()
print(df['word_count'].describe())
print((df['word_count'] < 5).sum(), "segments de moins de 5 mots")

count    9029.000000
mean       11.812382
std        11.426821
min         1.000000
25%         6.000000
50%         9.000000
75%        14.000000
max       235.000000
Name: word_count, dtype: float64
1418 segments de moins de 5 mots

In [11]:
print((df['word_count'] < 5).sum())
print((df['word_count'] == 0).sum())

1418
0

Keyness

In [91]:
import numpy as np

def keyness_log_likelihood(freq_group, total_group, freq_ref, total_ref):
    """
    freq_group : fréquence du topic dans le groupe (H ou F)
    total_group : total des tokens/topics dans le groupe
    freq_ref : fréquence dans le corpus de référence
    total_ref : total dans le corpus de référence
    """
    # Fréquences observées
    O1 = freq_group
    O2 = freq_ref - freq_group  # reste du corpus

    # Fréquences attendues
    E1 = total_group * (freq_ref / total_ref)
    E2 = (total_ref - total_group) * (freq_ref / total_ref)

    # Log-likelihood
    ll = 2 * (
        (O1 * np.log(O1 / E1) if O1 > 0 else 0) +
        (O2 * np.log(O2 / E2) if O2 > 0 else 0)
    )
    # Signe : positif = surreprésenté, négatif = sous-représenté
    sign = 1 if O1 / total_group > (freq_ref / total_ref) else -1
    return ll * sign

In [ ]:
# ath
for i in range(texts[texts["topic"]!=-1]["topic"].nunique()):
    k_h = keyness_log_likelihood(
        len(texts[(texts["g_ath"]=="H")&(texts["topic"]==i)]), len(texts[(texts["g_ath"]=="H")]),
        len(texts[(texts["topic"]==i)]), len(texts)
    )
    k_f = keyness_log_likelihood(
        len(texts[(texts["g_ath"]=="F")&(texts["topic"]==i)]), len(texts[(texts["g_ath"]=="F")]),
        len(texts[(texts["topic"]==i)]), len(texts)
    )
    texts.loc[texts.topic==i, "G_H_ath"] = k_h
    texts.loc[texts.topic==i, "G_F_ath"] = k_f

texts.loc[abs(texts.G_H_ath) > 3.84, "p-val_H_ath"] = 0.05
texts.loc[abs(texts.G_H_ath) > 6.63, "p-val_H_ath"] = 0.01
texts.loc[abs(texts.G_F_ath) > 3.84, "p-val_F_ath"] = 0.05
texts.loc[abs(texts.G_F_ath) > 6.63, "p-val_F_ath"] = 0.01

# com
for i in range(texts[texts["topic"]!=-1]["topic"].nunique()):
    k_h = keyness_log_likelihood(
        len(texts[(texts["main_g"]=="male")&(texts["topic"]==i)]), len(texts[(texts["main_g"]=="male")]),
        len(texts[(texts["topic"]==i)]), len(texts)
    )
    texts.loc[texts.topic==i, "G_H_com"] = k_h

texts.loc[abs(texts.G_H_com) > 3.84, "p-val_H_com"] = 0.05
texts.loc[abs(texts.G_H_com) > 6.63, "p-val_H_com"] = 0.01

In [107]:
texts[texts["label"]=="enthousiasme"]

,start,stop,text,main_speaker,main_g,audio_file,ID,g_ath,topic,topic_prob,label,G_H_ath,G_F_ath,p-val_H_ath,p-val_F_ath,G_H_com,G_F_com,p-val_H_com,p-val_F_com
67,527.76,557.04,'est magnifique ça,SPEAKER_00,female,CFTP5_wav.wav,CFTP5,F,61,1.0,enthousiasme,-1.356521,3.315191,NaN,NaN,5.838277,-5.838277,0.05,0.05
96,696.60,722.28,'est bien joué,SPEAKER_01,male,CFTP5_wav.wav,CFTP5,F,45,1.0,enthousiasme,14.404150,-5.811994,0.01,0.05,-7.090546,7.090546,0.01,0.01
113,0.00,30.00,très belle ambiance avec du monde dans les tr...,SPEAKER_00,male,CFPF_wav.wav,CFPF,F,56,1.0,enthousiasme,-4.594234,-0.236626,0.05,NaN,0.234061,-0.234061,NaN,NaN
274,901.30,955.22,'est bien il y a de la bonne vibe comme il y a...,SPEAKER_00,male,CFPF_wav.wav,CFPF,F,56,1.0,enthousiasme,-4.594234,-0.236626,0.05,NaN,0.234061,-0.234061,NaN,NaN
275,901.30,955.22,'s your vibe,SPEAKER_00,male,CFPF_wav.wav,CFPF,F,56,1.0,enthousiasme,-4.594234,-0.236626,0.05,NaN,0.234061,-0.234061,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11589,3399.78,3401.54,petite ligne c'est vraiment parfait oui,SPEAKER_01,male,CDMF_wav.wav,CDMF,M,47,1.0,enthousiasme,0.000948,-0.161281,NaN,NaN,0.442326,-0.442326,NaN,NaN
11660,3753.58,3791.34,il n'est pas dans ses habitudes,SPEAKER_00,male,CDMF_wav.wav,CDMF,M,56,1.0,enthousiasme,-4.594234,-0.236626,0.05,NaN,0.234061,-0.234061,NaN,NaN
11666,3753.58,3791.34,n'y a pas des fusions de joie superflues juste...,SPEAKER_00,male,CDMF_wav.wav,CDMF,M,56,1.0,enthousiasme,-4.594234,-0.236626,0.05,NaN,0.234061,-0.234061,NaN,NaN
11756,4229.48,4248.72,nous a réalisé des prouesses jusqu'à présent à...,SPEAKER_00,male,CDMF_wav.wav,CDMF,M,56,1.0,enthousiasme,-4.594234,-0.236626,0.05,NaN,0.234061,-0.234061,NaN,NaN
11872,4722.20,4819.36,l'émotion dans les tribunes il y avait les équ...,SPEAKER_00,male,CDMF_wav.wav,CDMF,M,56,1.0,enthousiasme,-4.594234,-0.236626,0.05,NaN,0.234061,-0.234061,NaN,NaN