Only to ensure Onyxia GPUs to work.

In [2]:
# Onyxia GPU compatible torch version
import sys
!{sys.executable} -m pip install torch==2.11.0 torchaudio torchvision \
    --index-url https://download.pytorch.org/whl/cu126 \
    --force-reinstall

Looking in indexes: https://download.pytorch.org/whl/cu126
Collecting torch==2.11.0
  Using cached torch-2.11.0%2Bcu126-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting torchaudio
  Using cached torchaudio-2.11.0%2Bcu126-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Collecting torchvision
  Using cached torchvision-0.26.0%2Bcu126-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting filelock (from torch==2.11.0)
  Using cached filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Collecting typing-extensions>=4.10.0 (from torch==2.11.0)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting setuptools<82 (from torch==2.11.0)
  Using cached setuptools-70.2.0-py3-none-any.whl.metadata (5.8 kB)
Collecting sympy>=1.13.3 (from torch==2.11.0)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch==2.11.0)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch==2.11.0)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=0.8.5 (from torch==2.11.0)
  Using cached fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting cuda-toolkit==12.6.3 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.6.3; platform_system == "Linux"->torch==2.11.0)
  Downloading cuda_toolkit-12.6.3-py2.py3-none-any.whl (2.3 kB)
Collecting cuda-bindings<13,>=12.9.4 (from torch==2.11.0)
  Using cached cuda_bindings-12.9.4-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch==2.11.0)
  Downloading nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl (706.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.8/706.8 MB 104.2 MB/s  0:00:0600:0100:01
Collecting nvidia-cusparselt-cu12==0.7.1 (from torch==2.11.0)
  Downloading nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl (287.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.2/287.2 MB 93.8 MB/s  0:00:03ta 0:00:01
Collecting nvidia-nccl-cu12==2.28.9 (from torch==2.11.0)
  Downloading nvidia_nccl_cu12-2.28.9-py3-none-manylinux_2_18_x86_64.whl (296.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.8/296.8 MB 99.9 MB/s  0:00:02:00:0100:01
Collecting nvidia-nvshmem-cu12==3.4.5 (from torch==2.11.0)
  Downloading nvidia_nvshmem_cu12-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (139.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.1/139.1 MB 99.9 MB/s  0:00:01ta 0:00:01
Collecting triton==3.6.0 (from torch==2.11.0)
  Using cached triton-3.6.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cublas-cu12==12.6.4.1.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.6.3; platform_system == "Linux"->torch==2.11.0)
  Downloading nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (393.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 MB 107.2 MB/s  0:00:0300:0100:01
Collecting nvidia-cuda-runtime-cu12==12.6.77.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.6.3; platform_system == "Linux"->torch==2.11.0)
  Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (897 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.7/897.7 kB 144.0 MB/s  0:00:00
Collecting nvidia-cufft-cu12==11.3.0.4.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.6.3; platform_system == "Linux"->torch==2.11.0)
  Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (200.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.2/200.2 MB 104.4 MB/s  0:00:0100:0100:01
Collecting nvidia-cufile-cu12==1.11.1.6.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.6.3; platform_system == "Linux"->torch==2.11.0)
  Downloading nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 145.5 MB/s  0:00:00
Collecting nvidia-cuda-cupti-cu12==12.6.80.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.6.3; platform_system == "Linux"->torch==2.11.0)
  Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 120.9 MB/s  0:00:00
Collecting nvidia-curand-cu12==10.3.7.77.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.6.3; platform_system == "Linux"->torch==2.11.0)
  Downloading nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 103.9 MB/s  0:00:00eta 0:00:01
Collecting nvidia-cusolver-cu12==11.7.1.2.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.6.3; platform_system == "Linux"->torch==2.11.0)
  Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (158.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.2/158.2 MB 106.9 MB/s  0:00:0100:0100:01
Collecting nvidia-cusparse-cu12==12.5.4.2.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.6.3; platform_system == "Linux"->torch==2.11.0)
  Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (216.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.6/216.6 MB 106.9 MB/s  0:00:02a 0:00:01
Collecting nvidia-nvjitlink-cu12==12.6.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.6.3; platform_system == "Linux"->torch==2.11.0)
  Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (19.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 118.1 MB/s  0:00:00
Collecting nvidia-cuda-nvrtc-cu12==12.6.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.6.3; platform_system == "Linux"->torch==2.11.0)
  Downloading nvidia_cuda_nvrtc_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (23.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.6/23.6 MB 116.8 MB/s  0:00:000:00:01
Collecting nvidia-nvtx-cu12==12.6.77.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.6.3; platform_system == "Linux"->torch==2.11.0)
  Downloading nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
Collecting cuda-pathfinder~=1.1 (from cuda-bindings<13,>=12.9.4->torch==2.11.0)
  Using cached cuda_pathfinder-1.2.2-py3-none-any.whl.metadata (3.2 kB)
Collecting numpy (from torchvision)
  Using cached numpy-2.4.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Using cached pillow-12.1.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch==2.11.0)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch==2.11.0)
  Using cached markupsafe-3.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Using cached torch-2.11.0%2Bcu126-cp313-cp313-manylinux_2_28_x86_64.whl (830.5 MB)
Using cached triton-3.6.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (188.3 MB)
Using cached cuda_bindings-12.9.4-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.9 MB)
Using cached cuda_pathfinder-1.2.2-py3-none-any.whl (23 kB)
Using cached setuptools-70.2.0-py3-none-any.whl (930 kB)
Using cached torchaudio-2.11.0%2Bcu126-cp313-cp313-manylinux_2_28_x86_64.whl (1.5 MB)
Using cached torchvision-0.26.0%2Bcu126-cp313-cp313-manylinux_2_28_x86_64.whl (7.3 MB)
Using cached fsspec-2026.2.0-py3-none-any.whl (202 kB)
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Using cached pillow-12.1.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached filelock-3.25.2-py3-none-any.whl (26 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Using cached numpy-2.4.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Installing collected packages: torchaudio, nvidia-cusparselt-cu12, mpmath, cuda-toolkit, typing-extensions, triton, sympy, setuptools, pillow, nvidia-nvtx-cu12, nvidia-nvshmem-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, networkx, MarkupSafe, fsspec, filelock, cuda-pathfinder, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, jinja2, cuda-bindings, nvidia-cusolver-cu12, torch, torchvision
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.11.0+cu126
    Uninstalling torchaudio-2.11.0+cu126:
      Successfully uninstalled torchaudio-2.11.0+cu126
  Attempting uninstall: nvidia-cusparselt-cu12━━  0/33 [torchaudio]
    Found existing installation: nvidia-cusparselt-cu12 0.7.10m [torchaudio]
    Uninstalling nvidia-cusparselt-cu12-0.7.1:0m  0/33 [torchaudio]
      Successfully uninstalled nvidia-cusparselt-cu12-0.7.1━━━━━━━  1/33 [nvidia-cusparselt-cu12]
  Attempting uninstall: mpmath━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/33 [nvidia-cusparselt-cu12]
    Found existing installation: mpmath 1.3.0━━━━━━━━━━━━━━━━━  1/33 [nvidia-cusparselt-cu12]
    Uninstalling mpmath-1.3.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/33 [nvidia-cusparselt-cu12]
      Successfully uninstalled mpmath-1.3.0━━━━━━━━━━━━━━━━━━━  1/33 [nvidia-cusparselt-cu12]
  Attempting uninstall: cuda-toolkit━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/33 [mpmath]arselt-cu12]
    Found existing installation: cuda-toolkit 12.6.3━━━━━━━━━━  2/33 [mpmath]
    Uninstalling cuda-toolkit-12.6.3:━━━━━━━━━━━━━━━━━━━━━━━━━  2/33 [mpmath]
      Successfully uninstalled cuda-toolkit-12.6.3━━━━━━━━━━━━  2/33 [mpmath]
  Attempting uninstall: typing-extensions━━━━━━━━━━━━━━━━━━━━━  2/33 [mpmath]
    Found existing installation: typing_extensions 4.15.0━━━━━  2/33 [mpmath]
    Uninstalling typing_extensions-4.15.0:━━━━━━━━━━━━━━━━━━━━  2/33 [mpmath]
      Successfully uninstalled typing_extensions-4.15.0━━━━━━━━━━━  4/33 [typing-extensions]
  Attempting uninstall: triton━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/33 [typing-extensions]
    Found existing installation: triton 3.6.0━━━━━━━━━━━━━━━━━  4/33 [typing-extensions]
    Uninstalling triton-3.6.0:90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/33 [triton]nsions]
      Successfully uninstalled triton-3.6.0━━━━━━━━━━━━━━━━━━━  5/33 [triton]
  Attempting uninstall: sympy[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/33 [triton]
    Found existing installation: sympy 1.14.0━━━━━━━━━━━━━━━━━  5/33 [triton]
    Uninstalling sympy-1.14.0:[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/33 [sympy]
      Successfully uninstalled sympy-1.14.0━━━━━━━━━━━━━━━━━━━━━━━  6/33 [sympy]
  Attempting uninstall: setuptools━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/33 [sympy]
    Found existing installation: setuptools 70.2.0━━━━━━━━━━━━  6/33 [sympy]
    Uninstalling setuptools-70.2.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/33 [sympy]
      Successfully uninstalled setuptools-70.2.0━━━━━━━━━━━━━━━━━━  7/33 [setuptools]
  Attempting uninstall: pillow━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  7/33 [setuptools]
    Found existing installation: pillow 12.1.1━━━━━━━━━━━━━━━━  7/33 [setuptools]
    Uninstalling pillow-12.1.1:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  7/33 [setuptools]
      Successfully uninstalled pillow-12.1.1━━━━━━━━━━━━━━━━━━  7/33 [setuptools]
  Attempting uninstall: nvidia-nvtx-cu12━━━━━━━━━━━━━━━━━━━━━━━━━━  8/33 [pillow]
    Found existing installation: nvidia-nvtx-cu12 12.6.77━━━━━  8/33 [pillow]
    Uninstalling nvidia-nvtx-cu12-12.6.77:━━━━━━━━━━━━━━━━━━━━  8/33 [pillow]
      Successfully uninstalled nvidia-nvtx-cu12-12.6.77━━━━━━━  8/33 [pillow]
  Attempting uninstall: nvidia-nvshmem-cu12━━━━━━━━━━━━━━━━━━━  8/33 [pillow]
    Found existing installation: nvidia-nvshmem-cu12 3.4.5━━━━  8/33 [pillow]
    Uninstalling nvidia-nvshmem-cu12-3.4.5:━━━━━━━━━━━━━━━━━━━  8/33 [pillow]
      Successfully uninstalled nvidia-nvshmem-cu12-3.4.5━━━━━━━━━━ 10/33 [nvidia-nvshmem-cu12]
  Attempting uninstall: nvidia-nvjitlink-cu12━━━━━━━━━━━━━━━━━━━━━ 10/33 [nvidia-nvshmem-cu12]
    Found existing installation: nvidia-nvjitlink-cu12 12.6.85 10/33 [nvidia-nvshmem-cu12]
    Uninstalling nvidia-nvjitlink-cu12-12.6.85:━━━━━━━━━━━━━━━ 10/33 [nvidia-nvshmem-cu12]
      Successfully uninstalled nvidia-nvjitlink-cu12-12.6.85━━ 10/33 [nvidia-nvshmem-cu12]
  Attempting uninstall: nvidia-nccl-cu12━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/33 [nvidia-nvjitlink-cu12]
    Found existing installation: nvidia-nccl-cu12 2.28.9━━━━━━ 11/33 [nvidia-nvjitlink-cu12]
    Uninstalling nvidia-nccl-cu12-2.28.9:━━━━━━━━━━━━━━━━━━━━━ 11/33 [nvidia-nvjitlink-cu12]
      Successfully uninstalled nvidia-nccl-cu12-2.28.9━━━━━━━━━━━━ 12/33 [nvidia-nccl-cu12]]
  Attempting uninstall: nvidia-curand-cu12━━━━━━━━━━━━━━━━━━━━━━━━ 12/33 [nvidia-nccl-cu12]
    Found existing installation: nvidia-curand-cu12 10.3.7.77━ 12/33 [nvidia-nccl-cu12]
    Uninstalling nvidia-curand-cu12-10.3.7.77:━━━━━━━━━━━━━━━━ 12/33 [nvidia-nccl-cu12]
      Successfully uninstalled nvidia-curand-cu12-10.3.7.77━━━ 12/33 [nvidia-nccl-cu12]
  Attempting uninstall: nvidia-cufile-cu12━━━━━━━━━━━━━━━━━━━━━━━━ 13/33 [nvidia-curand-cu12]
    Found existing installation: nvidia-cufile-cu12 1.11.1.6━━ 13/33 [nvidia-curand-cu12]
    Uninstalling nvidia-cufile-cu12-1.11.1.6:━━━━━━━━━━━━━━━━━ 13/33 [nvidia-curand-cu12]
      Successfully uninstalled nvidia-cufile-cu12-1.11.1.6━━━━ 13/33 [nvidia-curand-cu12]
  Attempting uninstall: nvidia-cuda-runtime-cu12━━━━━━━━━━━━━━ 13/33 [nvidia-curand-cu12]
    Found existing installation: nvidia-cuda-runtime-cu12 12.6.77m 13/33 [nvidia-curand-cu12]
    Uninstalling nvidia-cuda-runtime-cu12-12.6.77:━━━━━━━━━━━━ 13/33 [nvidia-curand-cu12]
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.6.77[0m 13/33 [nvidia-curand-cu12]
  Attempting uninstall: nvidia-cuda-nvrtc-cu12━━━━━━━━━━━━━━━━ 13/33 [nvidia-curand-cu12]
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.6.85[0m 13/33 [nvidia-curand-cu12]
    Uninstalling nvidia-cuda-nvrtc-cu12-12.6.85:━━━━━━━━━━━━━━ 13/33 [nvidia-curand-cu12]
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.6.85━━━━━ 16/33 [nvidia-cuda-nvrtc-cu12]
  Attempting uninstall: nvidia-cuda-cupti-cu12━━━━━━━━━━━━━━━━━━━━ 16/33 [nvidia-cuda-nvrtc-cu12]
    Found existing installation: nvidia-cuda-cupti-cu12 12.6.80━━━ 17/33 [nvidia-cuda-cupti-cu12]
    Uninstalling nvidia-cuda-cupti-cu12-12.6.80:━━━━━━━━━━━━━━ 17/33 [nvidia-cuda-cupti-cu12]
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.6.80━ 17/33 [nvidia-cuda-cupti-cu12]
  Attempting uninstall: nvidia-cublas-cu12m━━━━━━━━━━━━━━━━━━━ 17/33 [nvidia-cuda-cupti-cu12]
    Found existing installation: nvidia-cublas-cu12 12.6.4.1━━━━━━ 18/33 [nvidia-cublas-cu12]
    Uninstalling nvidia-cublas-cu12-12.6.4.1:━━━━━━━━━━━━━━━━━ 18/33 [nvidia-cublas-cu12]
      Successfully uninstalled nvidia-cublas-cu12-12.6.4.1━━━━ 18/33 [nvidia-cublas-cu12]
  Attempting uninstall: numpy╸━━━━━━━━━━━━━━━━━━ 18/33 [nvidia-cublas-cu12]
    Found existing installation: numpy 2.4.3━━━━━━━━━━━━━━━━━━ 18/33 [nvidia-cublas-cu12]
    Uninstalling numpy-2.4.3:╸━━━━━━━━━━━━━━━━━━ 18/33 [nvidia-cublas-cu12]
      Successfully uninstalled numpy-2.4.30m━━━━━━━━━━━━━━━━━━ 18/33 [nvidia-cublas-cu12]
  Attempting uninstall: networkx[0m╺━━━━━━━━━━━━━━━━ 19/33 [numpy]las-cu12]
    Found existing installation: networkx 3.6.1[90m━━━━━━━━━━━━━━━ 20/33 [networkx]
    Uninstalling networkx-3.6.1:╺━━━━━━━━━━━━━━━ 20/33 [networkx]
      Successfully uninstalled networkx-3.6.10m━━━━━━━━━━━━━━━ 20/33 [networkx]
  Attempting uninstall: MarkupSafe0m╺━━━━━━━━━━━━━━━ 20/33 [networkx]
    Found existing installation: MarkupSafe 3.0.3━━━━━━━━━━━━━ 20/33 [networkx]
    Uninstalling MarkupSafe-3.0.3:90m╺━━━━━━━━━━━━━━━ 20/33 [networkx]
      Successfully uninstalled MarkupSafe-3.0.3━━━━━━━━━━━━━━━ 20/33 [networkx]
  Attempting uninstall: fsspec━━━╺━━━━━━━━━━━━━━ 21/33 [MarkupSafe]
    Found existing installation: fsspec 2026.2.0━━━━━━━━━━━━━━ 21/33 [MarkupSafe]
    Uninstalling fsspec-2026.2.0:╺━━━━━━━━━━━━━━ 21/33 [MarkupSafe]
      Successfully uninstalled fsspec-2026.2.00m━━━━━━━━━━━━━━ 21/33 [MarkupSafe]
  Attempting uninstall: filelock━━╸━━━━━━━━━━━━━ 22/33 [fsspec]
    Found existing installation: filelock 3.25.2m━━━━━━━━━━━━━ 22/33 [fsspec]
    Uninstalling filelock-3.25.2:m╸━━━━━━━━━━━━━ 22/33 [fsspec]
      Successfully uninstalled filelock-3.25.290m━━━━━━━━━━━━━ 22/33 [fsspec]
  Attempting uninstall: cuda-pathfinder╸━━━━━━━━━━━━ 23/33 [filelock]
    Found existing installation: cuda-pathfinder 1.2.2━━━━━━━━ 23/33 [filelock]
    Uninstalling cuda-pathfinder-1.2.2:m╸━━━━━━━━━━━━ 23/33 [filelock]
      Successfully uninstalled cuda-pathfinder-1.2.2━━━━━━━━━━ 23/33 [filelock]
  Attempting uninstall: nvidia-cusparse-cu120m╺━━━━━━━━━━ 24/33 [cuda-pathfinder]
    Found existing installation: nvidia-cusparse-cu12 12.5.4.2 24/33 [cuda-pathfinder]
    Uninstalling nvidia-cusparse-cu12-12.5.4.2:━━━━━━━━━━ 24/33 [cuda-pathfinder]
      Successfully uninstalled nvidia-cusparse-cu12-12.5.4.2━━ 24/33 [cuda-pathfinder]
  Attempting uninstall: nvidia-cufft-cu12m╺━━━━━━━━━ 25/33 [nvidia-cusparse-cu12]
    Found existing installation: nvidia-cufft-cu12 11.3.0.4━━━ 25/33 [nvidia-cusparse-cu12]
    Uninstalling nvidia-cufft-cu12-11.3.0.4:━━━━━━━━━ 25/33 [nvidia-cusparse-cu12]
      Successfully uninstalled nvidia-cufft-cu12-11.3.0.4━━━━━ 25/33 [nvidia-cusparse-cu12]
  Attempting uninstall: nvidia-cudnn-cu120m╸━━━━━━━━ 26/33 [nvidia-cufft-cu12]
    Found existing installation: nvidia-cudnn-cu12 9.10.2.21━━━━━━ 27/33 [nvidia-cudnn-cu12]
    Uninstalling nvidia-cudnn-cu12-9.10.2.21:╸━━━━━━━ 27/33 [nvidia-cudnn-cu12]
      Successfully uninstalled nvidia-cudnn-cu12-9.10.2.21m━━━━━━━ 27/33 [nvidia-cudnn-cu12]
  Attempting uninstall: jinja2━━━━━━━━━━╸━━━━━━━ 27/33 [nvidia-cudnn-cu12]
    Found existing installation: Jinja2 3.1.6╸━━━━━━━ 27/33 [nvidia-cudnn-cu12]
    Uninstalling Jinja2-3.1.6:━━━━━━╸━━━━━━━ 27/33 [nvidia-cudnn-cu12]
      Successfully uninstalled Jinja2-3.1.61m╸━━━━━━━ 27/33 [nvidia-cudnn-cu12]
  Attempting uninstall: cuda-bindings━━━━╸━━━━━━ 28/33 [jinja2]n-cu12]
    Found existing installation: cuda-bindings 12.9.490m━━━━━━ 28/33 [jinja2]
    Uninstalling cuda-bindings-12.9.4:[0m╸━━━━━━ 28/33 [jinja2]
      Successfully uninstalled cuda-bindings-12.9.4m╺━━━━ 29/33 [cuda-bindings]
  Attempting uninstall: nvidia-cusolver-cu12[0m╺━━━━ 29/33 [cuda-bindings]
    Found existing installation: nvidia-cusolver-cu12 11.7.1.2 29/33 [cuda-bindings]
    Uninstalling nvidia-cusolver-cu12-11.7.1.2:m╺━━━━ 29/33 [cuda-bindings]
      Successfully uninstalled nvidia-cusolver-cu12-11.7.1.2━━ 29/33 [cuda-bindings]
  Attempting uninstall: torch━━━━━━━━━━━━━━━╺━━━ 30/33 [nvidia-cusolver-cu12]
    Found existing installation: torch 2.11.0+cu126[0m━━━ 30/33 [nvidia-cusolver-cu12]
    Uninstalling torch-2.11.0+cu126:━━━━━━━━━╸━━ 31/33 [torch]olver-cu12]

# Topic modeling

Here is our full implementation of BERTopic unsupervised modeling. The results of this section can be found in the results folder since a GPU is required to run this notebook quickly.
*Please note that if you try to run the code, the topics might have a different index than those in the report.*

Creation of the corpus dataframe.
*If you want to analyse another sport, please change the path accordingly.*

In [ ]:
import pandas as pd
import os

sport = "patin_art"
data_path = f"PESSD/csv/{sport}/"

df = pd.DataFrame()
for file in os.listdir(data_path):
    if file.endswith(".csv"):
        temp = pd.read_csv(os.path.join(data_path, file))
        df = pd.concat([df, temp])

Small preprocessing : removing non relevant texts, nouns, stopwords and splitting interventions into sentences.

In [56]:
import re
import string

# Removing music and noise (only technical commentary)
df = df[(df["main_g"]=="female")|(df["main_g"]=="male")]

# text to sentences
df["text"] = df["text"].apply(lambda x : x.split(". "))
df = df.explode("text")

# Removes all words with capitals
df["text"] = df["text"].apply(lambda x : re.sub(r"\s*[A-Z]\w*\s*", " ", x).strip())

# Removes empty texts
df = df[df["text"].str.strip() != ""]

# Remove punctuation
df ["text"] = df["text"].apply(lambda x : x.translate(str.maketrans('', '', string.punctuation.replace("'", ""))))

Adding metadata of the files (gender of the athletes).

In [57]:
df["ID"] = df["audio_file"].str.replace("_wav.wav","")
df = df.merge(pd.read_csv("metadata.csv"), on="ID")
df

,start,stop,text,main_speaker,main_g,audio_file,ID,g_ath
0,123.44,139.68,et pour une histoire racontée comme si on ét...,SPEAKER_03,female,PD2_wav.wav,PD2,M
1,123.44,139.68,choix musical de c'est vraiment pour créer ce...,SPEAKER_03,female,PD2_wav.wav,PD2,M
2,123.44,139.68,sais qu'il fait partie d'un de vos programmes...,SPEAKER_03,female,PD2_wav.wav,PD2,M
3,139.88,189.72,'est pour moi une des plus belles chorégraphie...,SPEAKER_04,female,PD2_wav.wav,PD2,M
4,139.88,189.72,pourquoi déjà le choix musical est très très b...,SPEAKER_04,female,PD2_wav.wav,PD2,M
...,...,...,...,...,...,...,...,...
7775,735.22,784.98,ça vous fait un bijou interprété par et,SPEAKER_02,female,PD1_wav.wav,PD1,M
7776,735.22,784.98,'est juste merveilleux,SPEAKER_02,female,PD1_wav.wav,PD1,M
7777,735.22,784.98,'est du cinéma sur glace,SPEAKER_02,female,PD1_wav.wav,PD1,M
7778,787.98,794.02,est très extravertie elle est absolument subli...,SPEAKER_00,female,PD1_wav.wav,PD1,M
7779,787.98,794.02,quelqu'un non,SPEAKER_00,female,PD1_wav.wav,PD1,M

Seeding to influence topic modeling according to common themes from the literature.

In [11]:
# AI made seed based on literature topics

seed = [
    # Famille
    [
        "famille", "père", "mère", "enfant", "fils", "fille",
        "parent", "frère", "sœur", "épouse", "mari", "foyer",
        "origines", "héritage", "soutien"
    ],
    
    # Émotions
    [
        "joie", "tristesse", "émotion", "larmes", "fierté",
        "peur", "stress", "pression", "bonheur", "souffrance",
        "passion", "frustration", "espoir", "déception", "soulagement"
    ],
    
    # Talent / Génie
    [
        "talent", "génie", "don", "prodige", "naturel",
        "instinct", "virtuose", "exceptionnel", "précocité", "surdoué",
        "facilité", "aisance"
    ],
    
    # Stratégie / Intelligence
    [
        "stratégie", "tactique", "intelligence", "compréhension", "lecture",
        "anticipation", "analyse", "vision", "décision", "placement",
        "lucidité", "maîtrise", "schéma"
    ],
    
    # Apparence / Esthétique
    [
        "apparence", "beauté", "grâce", "élégance", "style",
        "allure", "image", "charisme", "esthétique", "physique",
        "prestance", "posture"
    ],
    
    # Puissance / Physique
    [
        "puissance", "force", "vitesse", "explosivité", "athlétisme",
        "physique", "endurance", "corps", "muscles", "gabarit",
        "domination", "impact"
    ],
    
    # Travail / Résilience
    [
        "travail", "résilience", "effort", "abnégation", "sacrifice",
        "rigueur", "discipline", "persévérance", "régularité", "progression",
        "mental", "détermination", "volonté", "acharnement"
    ],
]

Prevalence of the seed in the corpus to see what topic is more likely to emerge.

In [58]:
from collections import Counter
words = [word for doc in df["text"] for word in doc.split()]
freq = Counter(words)
seed_names = ["famille", "émotion", "talent", "stratégie", "apparence", "puissance", "travail"]
for i in range(len(seed)):
    count = 0
    for word in seed[i] : 
        count += freq.get(word, 0)
    print(seed_names[i], " : ", count, " → ", count/len(df["text"]))

famille  :  55  →  0.007069408740359897
émotion  :  111  →  0.014267352185089975
talent  :  79  →  0.010154241645244215
stratégie  :  32  →  0.004113110539845758
apparence  :  90  →  0.011568123393316195
puissance  :  202  →  0.02596401028277635
travail  :  96  →  0.012339331619537276

Unserpervised topic model based on the corpus.
*If using CPU, please remove the "device" argument in* `SentenceTransformer`.

In [59]:
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP
import hdbscan

# Stopwords list
STOPWORDS = [x.strip() for x in open('stopwords.txt').readlines()]

# Docs 
docs = df["text"]

# Vectorizer for topic representation
vectorizer_model = CountVectorizer(
    stop_words=STOPWORDS,
    ngram_range=(1,2),
    min_df=2
    #token_pattern=r"\b(?!\w*[A-Z])\w+\b" # theoreticaly removes words with capital letters once embeddings are done
)

# To control for number and size of clusters
hdbscan_model = hdbscan.HDBSCAN(
    min_cluster_size=50,      # high for larger topics
    min_samples=10,
    cluster_selection_epsilon=0.1,
    cluster_selection_method='leaf',
    prediction_data=True
)

# Load CamemBERT embedding model
embedding_model = SentenceTransformer("dangvantuan/sentence-camembert-base", device="cuda") # remove device if CPU

# Build BERTopic model
topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    hdbscan_model=hdbscan_model,
    language="french",
    calculate_probabilities=True,
    verbose=True,
    seed_topic_list=seed    
)

# Fit the model
topics, probs = topic_model.fit_transform(docs)

# Show discovered topics
# print(topic_model.get_topic_info())

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3741.25it/s]
2026-05-10 13:01:27,204 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 244/244 [00:09<00:00, 25.77it/s]
2026-05-10 13:01:36,721 - BERTopic - Embedding - Completed ✓
2026-05-10 13:01:36,722 - BERTopic - Guided - Find embeddings highly related to seeded topics.
Batches: 100%|██████████| 1/1 [00:00<00:00, 50.18it/s]
2026-05-10 13:01:36,961 - BERTopic - Guided - Completed ✓
2026-05-10 13:01:36,962 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-10 13:02:14,452 - BERTopic - Dimensionality - Completed ✓
2026-05-10 13:02:14,454 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-10 13:02:15,451 - BERTopic - Cluster - Completed ✓
2026-05-10 13:02:15,460 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-10 13:02:15,602 - BERTopic - Representation - Completed ✓

Visualization of the topic hierarchy.

In [62]:
# Visualize topic hierarchy
topic_model.visualize_hierarchy()

Adding topics and topic probabilites to the corpus dataframe.

In [60]:
df["topic"] = topics
df["topic_prob"] = probs.max(axis=1)

Saving text to topic allocation.

In [ ]:
df.to_csv(f"s3://lab/PESSD/results/{sport}/text2topics.csv")

To summerise the information, the share of commentary on women(*F*), men (*H*) and both (*M*) are computed by topic.

In [63]:
# Only classified docs
clf = df[df["topic"]!=-1]
adf = pd.DataFrame()
for i in clf["topic"].unique() :
    tmp = df[df["topic"]==i]
    tmp = tmp["g_ath"].value_counts(normalize=True)
    tmp = pd.DataFrame([{
    "topic": f"topic_{i}",
    "M": tmp.get("M", 0),
    "F": tmp.get("F", 0),
    "H": tmp.get("H", 0)
}])
    adf = pd.concat([adf,tmp])

# All topics
tmp = clf["g_ath"].value_counts(normalize=True)
tmp = pd.DataFrame([{
    "topic": "all_topics",
    "M": tmp.get("M", 0),
    "F": tmp.get("F", 0),
    "H": tmp.get("H", 0)
}])
adf = pd.concat([adf,tmp])

for col in ["M", "F", "H"]:
    ref = tmp[col]
    adf[f"{col}_diff"] = adf[col] - ref
    adf[f"{col}_diff"] = adf[f"{col}_diff"].apply(
        lambda x: f"{x*100:+.1f}%" if pd.notna(x) else ""
    )

adf.sort_values(
    by='topic',
    key=lambda s: s.str.extract(r'(\d+)')[0].astype(float).fillna(-1)
).head()

        topic         M         F         H  M_diff  F_diff  H_diff
0  all_topics  0.538760  0.253835  0.207404   +0.0%   +0.0%   +0.0%
0     topic_0  0.457983  0.268908  0.273109   -8.1%   +1.5%   +6.6%
0     topic_1  0.790393  0.139738  0.069869  +25.2%  -11.4%  -13.8%
0     topic_2  0.400000  0.231818  0.368182  -13.9%   -2.2%  +16.1%
0     topic_3  0.444444  0.365741  0.189815   -9.4%  +11.2%   -1.8%

One can follow the same logic but with the gender of the commentator.

In [21]:
# Only classified docs
df["main_g"] = df["main_g"].map({"male" : "H", "female" : "F"})
clf = df[df["topic"]!=-1]
cdf = pd.DataFrame()
for i in clf["topic"].unique() :
    tmp = df[df["topic"]==i]
    tmp = tmp["main_g"].value_counts(normalize=True)
    tmp = pd.DataFrame([{
    "topic": f"topic_{i}",
    "F": tmp.get("F", 0),
    "H": tmp.get("H", 0)
}])
    cdf = pd.concat([cdf,tmp])

# All topics
tmp = clf["main_g"].value_counts(normalize=True)
tmp = pd.DataFrame([{
    "topic": "all_topics",
    "F": tmp.get("F", 0),
    "H": tmp.get("H", 0)
}])
cdf = pd.concat([cdf,tmp])

for col in ["F", "H"]:
    ref = tmp[col]
    cdf[f"{col}_diff"] = cdf[col] - ref
    cdf[f"{col}_diff"] = cdf[f"{col}_diff"].apply(
        lambda x: f"{x*100:+.1f}%" if pd.notna(x) else ""
    )

cdf.sort_values(
    by='topic',
    key=lambda s: s.str.extract(r'(\d+)')[0].astype(float).fillna(-1)
).head()

        topic         F         H  F_diff  H_diff
0  all_topics  0.528351  0.471649   +0.0%   +0.0%
0     topic_0  0.515823  0.484177   -1.3%   +1.3%
0     topic_1  0.550000  0.450000   +2.2%   -2.2%
0     topic_2  0.396552  0.603448  -13.2%  +13.2%
0     topic_3  0.734597  0.265403  +20.6%  -20.6%

Saving descriptive statistics.

In [ ]:
adf.to_csv(f"s3://lab/PESSD/results/{sport}/athlete_gender.csv")
cdf.to_csv(f"s3://lab/PESSD/results/{sport}/commentator_gender.csv")

In [ ]:
# Save locally first
topic_model.save(
    "./bert_model",
    serialization="pytorch",
    save_ctfidf=False,
    save_embedding_model=embedding_model
)

fs.put("./bert_model", f"s3://lab/PESSD/results/{sport}/bert_model", recursive=True)

[None, None, None]

To see if the topics are consistent, we run the model without 20% of the corpus.
*GPU here is mandatory.*

In [66]:
# Main words of current model themes

reference = dict()
for topic_id in topic_model.get_topics():
    if topic_id == -1:
        continue
    words = [w for w, _ in topic_model.get_topic(topic_id)[:10]]
    reference[topic_id] = tuple(sorted(words))

10 runs at 80%. Stability is measured with the Jaccard Index between reference model topics and 80% runs topics. If the index is higher than 0.2, 7 times or more, the topic is considered stable.

In [ ]:
from sklearn.utils import resample
from collections import Counter

# List of words for each topic for each model
all_topics_words = []

# Number of runs
nb_iter = 10

for i in range(nb_iter):

    # First, resample 80% of docs
    sample = resample(docs, n_samples=int(len(docs) * 0.8), random_state=i)

    # Same model specification
    model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    hdbscan_model=hdbscan_model,
    language="french",
    calculate_probabilities=True,
    verbose=True,
    seed_topic_list=None    
)
    model.fit(sample)
    
    # Top 10 words per topic
    top_words = set()
    for topic_id in model.get_topics():
        if topic_id == -1:
            continue
        words = [w for w, _ in model.get_topic(topic_id)[:10]]
        top_words.add(tuple(sorted(words)))
    
    all_topics_words.append(top_words)


# Jaccard similarity index
def jaccard(t1, t2):
    s1, s2 = set(t1), set(t2)
    return len(s1 & s2) / len(s1 | s2)

# Topic stability
"""
Measures similarity between reference topic and topics found in other runs.

Thresholds for stability are determined by Jaccard index (threshold) and number of occurences (min_run)
"""
def is_stable(topic, all_runs, threshold=0.2, min_runs=7):
    count = 0
    for run_topics in all_runs:
        if any(jaccard(topic, t) >= threshold for t in run_topics):
            count += 1
    return count >= min_runs

stable_topics = dict()
for topic_id in reference : 
    if is_stable(reference[topic_id], all_topics_words) : 
        stable_topics[topic_id] = reference[topic_id]

print(f"Stable topics (≥7 runs out of 10) : {len(stable_topics)}")
for t in stable_topics:
    print(stable_topics[t])

2026-05-10 13:04:06,220 - BERTopic - Embedding - Transforming documents to embeddings.
Batches:   0%|          | 0/219 [00:00<?, ?it/s]

Batches: 100%|██████████| 219/219 [00:08<00:00, 26.42it/s]
2026-05-10 13:04:14,549 - BERTopic - Embedding - Completed ✓
2026-05-10 13:04:14,550 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-10 13:04:51,541 - BERTopic - Dimensionality - Completed ✓
2026-05-10 13:04:51,543 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-10 13:04:52,489 - BERTopic - Cluster - Completed ✓
2026-05-10 13:04:52,495 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-10 13:04:52,611 - BERTopic - Representation - Completed ✓
2026-05-10 13:04:52,789 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 219/219 [00:08<00:00, 25.87it/s]
2026-05-10 13:05:01,294 - BERTopic - Embedding - Completed ✓
2026-05-10 13:05:01,295 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-10 13:05:41,194 - BERTopic - Dimensionality - Completed ✓
2026-05-10 13:05:41,197 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-10 13:05:42,236 - BERTopic - Cluster - Completed ✓
2026-05-10 13:05:42,243 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-10 13:05:42,371 - BERTopic - Representation - Completed ✓
2026-05-10 13:05:42,551 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 219/219 [00:08<00:00, 25.47it/s]
2026-05-10 13:05:51,189 - BERTopic - Embedding - Completed ✓
2026-05-10 13:05:51,190 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-10 13:06:33,456 - BERTopic - Dimensionality - Completed ✓
2026-05-10 13:06:33,459 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-10 13:06:34,272 - BERTopic - Cluster - Completed ✓
2026-05-10 13:06:34,284 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-10 13:06:34,399 - BERTopic - Representation - Completed ✓
2026-05-10 13:06:34,551 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 219/219 [00:08<00:00, 25.73it/s]
2026-05-10 13:06:43,105 - BERTopic - Embedding - Completed ✓
2026-05-10 13:06:43,106 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-10 13:07:18,163 - BERTopic - Dimensionality - Completed ✓
2026-05-10 13:07:18,165 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-10 13:07:19,214 - BERTopic - Cluster - Completed ✓
2026-05-10 13:07:19,219 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-10 13:07:19,339 - BERTopic - Representation - Completed ✓
2026-05-10 13:07:19,512 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 219/219 [00:08<00:00, 25.37it/s]
2026-05-10 13:07:28,183 - BERTopic - Embedding - Completed ✓
2026-05-10 13:07:28,184 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-10 13:08:06,289 - BERTopic - Dimensionality - Completed ✓
2026-05-10 13:08:06,290 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-10 13:08:07,193 - BERTopic - Cluster - Completed ✓
2026-05-10 13:08:07,198 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-10 13:08:07,315 - BERTopic - Representation - Completed ✓
2026-05-10 13:08:07,481 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 219/219 [00:08<00:00, 25.40it/s]
2026-05-10 13:08:16,138 - BERTopic - Embedding - Completed ✓
2026-05-10 13:08:16,139 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-10 13:08:55,576 - BERTopic - Dimensionality - Completed ✓
2026-05-10 13:08:55,579 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-10 13:08:56,493 - BERTopic - Cluster - Completed ✓
2026-05-10 13:08:56,499 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-10 13:08:56,616 - BERTopic - Representation - Completed ✓
2026-05-10 13:08:56,785 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 219/219 [00:08<00:00, 25.31it/s]
2026-05-10 13:09:05,477 - BERTopic - Embedding - Completed ✓
2026-05-10 13:09:05,479 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-10 13:09:46,363 - BERTopic - Dimensionality - Completed ✓
2026-05-10 13:09:46,365 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-10 13:09:47,283 - BERTopic - Cluster - Completed ✓
2026-05-10 13:09:47,289 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-10 13:09:47,404 - BERTopic - Representation - Completed ✓
2026-05-10 13:09:47,579 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 219/219 [00:08<00:00, 25.65it/s]
2026-05-10 13:09:56,152 - BERTopic - Embedding - Completed ✓
2026-05-10 13:09:56,153 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-10 13:10:37,689 - BERTopic - Dimensionality - Completed ✓
2026-05-10 13:10:37,691 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-10 13:10:38,724 - BERTopic - Cluster - Completed ✓
2026-05-10 13:10:38,729 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-10 13:10:38,860 - BERTopic - Representation - Completed ✓
2026-05-10 13:10:39,056 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 219/219 [00:08<00:00, 25.18it/s]
2026-05-10 13:10:48,503 - BERTopic - Embedding - Completed ✓
2026-05-10 13:10:48,504 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-10 13:11:31,077 - BERTopic - Dimensionality - Completed ✓
2026-05-10 13:11:31,078 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-10 13:11:32,004 - BERTopic - Cluster - Completed ✓
2026-05-10 13:11:32,014 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-10 13:11:32,134 - BERTopic - Representation - Completed ✓
2026-05-10 13:11:32,305 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 219/219 [00:08<00:00, 25.56it/s]
2026-05-10 13:11:40,926 - BERTopic - Embedding - Completed ✓
2026-05-10 13:11:40,927 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-10 13:12:23,778 - BERTopic - Dimensionality - Completed ✓
2026-05-10 13:12:23,780 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-10 13:12:24,694 - BERTopic - Cluster - Completed ✓
2026-05-10 13:12:24,700 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-10 13:12:24,820 - BERTopic - Representation - Completed ✓

Stable topics (≥7 runs out of 10) : 21
('ensemble', 'film', 'patinage', 'patinent', 'patiner', 'patineur', 'patineurs', 'patineuse', 'patineuses', 'patiné')
('années', 'couple', 'couples', 'disait', 'ensemble', 'génération', 'histoire', 'jeune', 'jeunes', 'progression')
('lancé', 'lutz', 'parallèle', 'quadruple', 'quadruples', 'salco', 'saut', 'sauts', 'triple', 'triple salco')
('bronze', 'champion', 'champion monde', 'championne', 'championne monde', 'monde', 'médaille', 'olympique', 'olympiques', 'titre')
('', '', '', '', '', '', '', '', '', 'trouvé')
('compétition', 'cut', 'demain', 'event', 'finale', 'libre', 'team', 'team event', 'épreuve', 'équipe')
('court', 'dames', 'exceptionnel', 'libre', 'meilleur', 'programme', 'programme court', 'programme libre', 'programmes', 'tête programme')
('3e', '3e place', '4e', 'instant', 'place', 'place provisoire', 'podium', 'podium provisoire', 'prennent', 'provisoire')
('axe', 'axel', 'demi', 'rotation', 'tour', 'tour tours', 'tours', 'tours demi', 'tours tours', 'triple axel')
('centre', 'coach', 'entraîne', 'entraînement', 'entraînements', 'entraînent', 'entraîneur', 'entraîneurs', 'forme', 'équipe')
('air', 'combinaison', 'niveau', 'partie', 'petit', 'points', 'saut', 'sauts', 'technique', 'triple')
('90', 'années', 'chorégraphe', 'chorégraphes', 'chorégraphie', 'danse', 'recherche', 'rythme', 'rythme danse', 'travail')
('bande', 'bande originale', 'chanson', 'choix', 'choix musical', 'film', 'message', 'musical', 'musique', 'originale')
('compétition', 'instant', 'instant tête', 'place', 'remonter', 'tiennent', 'tient', 'tient tête', 'tête', 'tête compétition')
('70', 'battent', 'battu', 'meilleur', 'meilleur score', 'record', 'saison', 'score', 'score saison', 'score score')
('bonus', 'bonus malus', 'donner', 'juges', 'jury', 'malus', 'points', 'technique', 'technique technique', 'élément')
('excellent', 'niveau', 'niveau niveau', 'niveau technique', 'note technique', 'scorer', 'technique', 'technique excellent', 'technique niveau', 'technique technique')
('exceptionnel', 'extraordinaire', 'extraordinaires', 'fabuleux', 'fantastique', 'impressionnant', 'incroyable', 'incroyable exceptionnel', 'incroyable incroyable', 'surprenant')
('2e note', '2ème', '2ème note', 'audessus', 'monte', 'monter', 'niveau note', 'note', 'note note', 'notes')
('2022', '2023', '2024', '2025', 'bronze', 'champion', 'championne', 'double champion', 'monde', 'médailles')
('beauté', 'doux', 'extraordinaires', 'magique', 'magnifique', 'merveille', 'merveilleux', 'sublime', 'trouve', 'voir technique')

Save stable topics.

In [ ]:
pd.DataFrame.from_dict(stable_topics).to_csv(f"s3://lab/PESSD/results/{sport}/stable_topics.csv")

Exploration of topics content to assess the theme from literature to which they correspond.

In [76]:
# Sentences of topic i and by sport
for _, j in df[df["topic"]==39][["text","ID"]].iterrows():
    print(j["ID"],"_", j["text"])

PD2 _ les qui arrivent
ECC _ position est parfaite mais j'aimerais bien voir l'arrivée
ECC _ ce que l'arrivée est belle  est bien
ECC _ avec une arrivée pas tout à fait parfaite
PCH _ je suis d'accord pour voir l'arrivée
PCH _ 1 2 3 4 et c'est propre à l'arrivée
PCH _ des petits détails regardez l'arrivée
PCH _ l'arrivée c'est propre
PCH _ voyez comme l'arrivée est parfaite
EDR _ n'était pas complètement propre à mon avis
ELF _ regarde l'arrivée c'est pas net
ELC _ parce qu'il y a une petite épaule à l'arrivée
ELC _ se bat sur ses seaux
ELC _ il n'y aura encore pas le maximum je pense parce qu'il y a un petit touch à l'arrivée
ELC _ contrôle l'arrivée
ELC _ 'est beau il n'y a aucune bascule à l'arrivée
DR1 _ n'était pas complètement propre à mon avis
DR1 _ ce que l'arrivée est belle  est bien
DR1 _ 'arrivée elle est bonne
DR1 _ souhaite aussi regarder si la lame à l'arrivée c'est un petit peu moyen
DR1 _ la lame à l'arrivée
DR1 _ 'arrivée est absolument parfaite
DR1 _ ne nous mettait même pas ses seaux
ECF _ 'arrivée elle est bonne
ECF _ souhaite aussi regarder si la lame à l'arrivée c'est un petit peu moyen
ECF _ la lame à l'arrivée
ECF _ y avait un petit appel un petit doute moi je n'avais pas de doute l'arrivée est absolument parfaite c'est pirouette aussi
ECF _ ne mettait même pas ses seaux
ECF _ à l'arrivée
ECF _ sur une arrivée du
DR2 _ sur une arrivée du
PCTH _ 'arrivée est absolument parfaite
PCTH _ 'arrivée très en avant
PCTH _ mettra des petits malus parce que l'arrivée n'est pas glissée esthétique
PCTH _ glisse et l'arrivée
PLF _ l'arrivée
PLF _ il a un papier pas d'arrivée
PAC _ cette confiance à chaque arrivée
PAC _ on arrive avec des
PAC _ 'arrivée est parfaite
PLH _ 'est vrai que ces arrivées n'étaient pas souvent nettes
PLH _ nous a habitué à des remontes à dents
PAD _ l'arrivée
PAD _ l'arrivée
PAD _ je le mets je le dégrade un petit peu parce que l'arrivée n'est pas
PAD _ y a une petite accroche à l'arrivée
PAF _ 'est l'arrivée parfaite
PAF _ croisé de pied jusqu'à la réception c'est propre
PAF _ 'est un petit peu moins propre
PAF _ ça c'est propre c'est net
PAF _ 'arrivée est absolument parfaite avec une gestuelle un sourire

In [72]:
topic_model.get_topic(3)

[('skis', np.float64(0.16361049412552794)),
 ('ski', np.float64(0.10559824368349971)),
 ('temps ski', np.float64(0.05943967232844046)),
 ('rapide', np.float64(0.04660091031383716)),
 ('rapide skis', np.float64(0.04097807861909089)),
 ('vite skis', np.float64(0.04058543096293472)),
 ('neige', np.float64(0.03868430085931936)),
 ('vite', np.float64(0.033448909976096286)),
 ('temps', np.float64(0.028506636788974853)),
 ('skier', np.float64(0.027409247184059172))]

Manual labelization based on topic content and literature topics.

In [ ]:
# biath
"""
label = {
    29 : "stratégie", 35 : "stratégie",
    17 : "enthousiasme", 20 : "enthousiasme", 21 : "enthousiasme", 26 : "enthousiasme",
    9 : "forme", 16 : "forme", 46 : "forme",
    8 : "émotion",
    2 : "NA", 7 : "NA", 27 : "NA", 37 : "NA", 14 : "NA", 39 : "NA", 42 : "NA",
    5 : "effort", 32 : "effort",
    1 : "compétition", 4 : "compétition", 6 : "compétition", 12 : "compétition", 24 : "compétition", 34 : "compétition",
    0 : "sport", 3 : "sport", 10 : "sport", 11 : "sport", 13 : "sport", 15 : "sport", 18 : "sport", 19 : "sport", 22 : "sport", 23 : "sport", 25 : "sport", 30 : "sport", 31 : "sport", 43 : "sport", 44 : "sport", 45 : "sport", 28 : "sport", 33 : "sport", 36 : "sport", 38 : "sport", 40 : "sport", 41 : "sport", 47 : "sport"
}"""

# curl
"""
label = {
    0: "sport", 1: "sport", 4: "sport", 7: "sport", 8: "sport",
    11: "sport", 14: "sport", 17: "sport", 19: "sport", 24: "sport",
    25: "sport", 31: "sport", 33: "sport", 36: "sport", 39: "sport",
    40: "sport", 41: "sport", 42: "sport", 43: "sport", 46: "sport",
    49: "sport", 50: "sport", 52: "sport", 54: "sport", 55: "sport",
    63: "sport", 12: "sport", 13: "sport", 18: "sport", 20: "sport",
    21: "sport", 23: "sport", 26: "sport", 27: "sport", 29: "sport",
    30: "sport", 48: "sport", 59: "sport", 60: "sport", 64: "sport",
    3: "compétition", 5: "compétition", 16: "compétition",
    32: "compétition", 37: "compétition", 38: "compétition",
    9: "NA", 44: "NA", 58: "NA", 2: "NA", 6: "NA", 10: "NA",
    22: "NA", 28: "NA", 35: "NA", 51: "NA", 53: "NA", 57: "NA",
    62: "NA", 65: "NA",
    61: "enthousiasme", 45: "enthousiasme", 47: "enthousiasme", 56: "enthousiasme",
    15: "stratégie",
    34: "émotion"
}
"""

# patin_art
"""
label = {
    0: "sport", 1: "sport", 2: "sport", 8: "sport", 10: "sport",
    11: "sport", 12: "sport", 15: "sport", 18: "sport", 22: "sport",
    23: "sport", 25: "sport", 26: "sport", 27: "sport", 28: "sport",
    29: "sport", 30: "sport", 32: "sport", 33: "sport", 37: "sport",
    41: "sport", 21: "sport", 34: "sport", 39: "sport",
    4: "compétition", 36: "compétition",
    5: "émotion", 20: "émotion",
    13: "privé", 35: "privé",
    14: "esprit",
    24: "apparence",
    16: "enthousiasme", 31: "enthousiasme", 40: "enthousiasme",
    17: "forme",
    6: "NA", 9: "NA", 3: "NA", 7: "NA", 19: "NA", 38: "NA",
}
"""

# patin_vit

"""
label = {
    2: "sport", 3: "sport", 4: "sport", 9: "sport", 14: "sport",
    15: "sport", 16: "sport", 17: "sport", 18: "sport", 19: "sport",
    20: "sport", 22: "sport", 24: "sport", 12: "sport", 25: "sport",
    27: "sport",
    5: "compétition", 8: "compétition", 26: "compétition",
    6: "effort",
    1: "enthousiasme",
    10: "émotion",
    0: "NA", 11: "NA", 13: "NA", 21: "NA",
    7: "forme", 23: "forme"
}
"""

# ski_alp
"""
label = {
    1 : "sport", 3 : "sport", 4 : "sport",
    2 : "compétition",
    0 : "NA"
}"""

#ski_free
"""
label = {
    2: "sport", 3: "sport", 4: "sport", 9: "sport", 11: "sport",
    15: "sport", 20: "sport", 21: "sport", 34: "sport", 35: "sport",
    40: "sport", 7: "sport", 10: "sport", 16: "sport", 17: "sport",
    19: "sport", 25: "sport", 27: "sport", 31: "sport", 37: "sport",
    38: "sport", 33: "sport",
    5: "compétition", 23: "compétition", 28: "compétition",
    39: "compétition",
    12: "enthousiasme", 29: "enthousiasme", 32: "enthousiasme",
    22: "émotion",
    18: "effort",
    41: "privé",
    0: "NA", 1: "NA", 6: "NA", 8: "NA", 13: "NA", 14: "NA",
    26: "NA", 24: "NA", 30: "NA", 36: "NA",
}
"""

'\nlabel = {\n    2: "sport", 3: "sport", 4: "sport", 9: "sport", 11: "sport",\n    15: "sport", 20: "sport", 21: "sport", 34: "sport", 35: "sport",\n    40: "sport", 7: "sport", 10: "sport", 16: "sport", 17: "sport",\n    19: "sport", 25: "sport", 27: "sport", 31: "sport", 37: "sport",\n    38: "sport", 33: "sport",\n    5: "compétition", 23: "compétition", 28: "compétition",\n    39: "compétition",\n    12: "enthousiasme", 29: "enthousiasme", 32: "enthousiasme",\n    22: "émotion",\n    18: "effort",\n    41: "privé",\n    0: "NA", 1: "NA", 6: "NA", 8: "NA", 13: "NA", 14: "NA",\n    26: "NA", 24: "NA", 30: "NA", 36: "NA",\n}'

In [78]:
print(len(sorted(list(label.keys()))))

42

In [ ]:
pd.DataFrame([label]).to_csv(f"s3://lab/PESSD/results/{sport}/labels.csv")